cfg = {

    pesoMax = 50,

    client = {
        blur = exports['crp_blur'], -- O nome do script de blur ou deixe false caso não queira.
        fastUse = true, -- Usar o item clicando com o botão direito em cima dele.
        actionBar = true, -- Slots rápidos
    },

    objects = {
        ['pizza'] = {
            model = 2881,
            position = {-0.07,0.14,0.13,-14.4,-7.2,180},
            bone = 26,
        },
        ['hamburguera'] = {
            model = 2703,
            position = {0,0.05,0,0,0,180},
            bone = 26,
        },
        ['hamburguerb'] = {
            model = 2703,
            position = {0,0.05,0,0,0,180},
            bone = 26,
        },
        ['hamburguerc'] = {
            model = 2703,
            position = {0,0.05,0,0,0,180},
            bone = 26,
        },
        ['agua'] = {
            model = 1856,
            position = {0,-0.1,0.1,0,180,82.8},
            bone = 36,
            scale = 0.5,
        },
        ['sucouva'] = {
            model = 1964,
            position = {0.02,0.07,-0.01,0,180,111.6},
            bone = 36,
        },
        ['sucobanana'] = {
            model = 1964,
            position = {0.02,0.07,-0.01,0,180,111.6},
            bone = 36,
        },
        ['cbnuggets'] = {
            model = 2768,
            position = {0,0,0,0,0,18},
            bone = 26,
        },
        ['cbfritas'] = {
            model = 2768,
            position = {0,0,0,0,0,18},
            bone = 26,
        },
        ['cbcebola'] = {
            model = 2768,
            position = {0,0,0,0,0,18},
            bone = 26,
        },
        ['cbrefri'] = {
            model = 2647,
            position = {0,0.04,-0.05,0,169.2,3.6},
            bone = 36,
            scale = 0.7,
        },
        ['twrefri'] = {
            model = 2647,
            position = {0,0.04,-0.05,0,169.2,3.6},
            bone = 36,
            scale = 0.7,
        },
        
    },

    blockedItems = { -- Items que caso você morra voce não vai perder.
        ['mascarah'] = true, 
        ['mascara-3-1'] = true, 
        ['mascara-1-1'] = true, 
        ['mascara-2-1'] = true
    },

    items = {
        -- << ALIMENTOS >>
        ['agua'] = {nome = 'Água', peso = 0.1, type = 'bebida'},
        ['banana'] = {nome = 'Banana', peso = 0.1, type = 'comida'},
        ['uva'] = {nome = 'Uva', peso = 0.1, type = 'comida'},
        ['sucouva'] = {nome = 'Suco de Uva', peso = 0.1, type = 'bebida'},
        ['sucobanana'] = {nome = 'Vitamina de Banana', peso = 0.1, type = 'bebida'},
        ['sprunk'] = {nome = 'Sprunk', peso = 0.1, type = 'bebida'},
        ['sprite'] = {nome = 'Sprite', peso = 0.1, type = 'bebida'},
        ['garrafavazia'] = {nome = 'Garrafa Vazia', peso = 0.1},
        ['chips'] = {nome = 'Chips', peso = 0.1, type = 'comida'},
        ['cola'] = {nome = 'Coca Cola', peso = 0.1, type = 'comida'},
        ['energetico'] = {nome = 'Energético', peso = 0.1, type = 'bebida'},
        ['hamburguera'] = {nome = 'Hamburguer Grande', peso = 0.4, type = 'comida'},
        ['hamburguerb'] = {nome = 'Hamburguer Medio', peso = 0.2, type = 'comida'},
        ['hamburguerc'] = {nome = 'Hamburguer Pequeno', peso = 0.1, type = 'comida'},
        ['pao'] = {nome = 'Pão', peso = 0.2, type = 'comida'},
        ['frango'] = {nome = 'Pedaços de Frango', peso = 1.0, type = 'comida'},
        ['frangoempanado'] = {nome = 'Frango Empanado', peso = 0.2, type = 'comida'},
        ['alface'] = {nome = 'Folha de Alface', peso = 0.1, type = 'comida'},
        --CluckinBell
        ['cbnuggets'] = {nome = 'Nuggets', peso = 0.4, type = 'comida'},
        ['cbburguer'] = {nome = 'Chicken Burguer', peso = 0.5, type = 'comida'},
        ['frangofrito'] = {nome = 'Balde Frango Frito', peso = 1.0, type = 'comida'},
        ['cbfritas'] = {nome = 'Batata Frita', peso = 0.4, type = 'comida'},
        ['cbcebola'] = {nome = 'Anéis de Cebola', peso = 0.4, type = 'comida'},
        ['cbrefri'] = {nome = 'Refrigerante', peso = 0.4, type = 'bebida'},
        ['cbpacote'] = {nome = 'Sacola CluckinBell', peso = 0.5, type = 'bau'},
        ['cbcombo'] = {nome = 'Sacola', peso = 1.0},
        --PIZZARIA
        ['twcombo'] = {nome = 'Sacola', peso = 1.0},
        ['pizza'] = {nome = 'Fatia de Pizza', peso = 0.4, type = 'comida'},
        ['twfritas'] = {nome = 'T.W.S Batata Frita', peso = 0.5, type = 'comida'},
        ['twrefri'] = {nome = 'T.W.S Refrigerante', peso = 0.4, type = 'bebida'},

        --HALLOWEEN
        ['doces'] = {nome = 'Doces', peso = 0.0},
        ['baldeh'] = {nome = 'Balde Halloween', peso = 1.0},

        -- documentos 
        ['identidade'] = {nome = 'Identidade', peso = 0.02, document = true, id = true, desc = "Descrição: Identidade nacional de San Andreas"},
        ['distintivo'] = {nome = 'Distintivo LSPD', peso = 0.02, document = true, id = true},
        

        -- << INGEDIENTES >> --
        ['molhopizza'] = {nome = 'Molho de pizza', peso = 1.0},
        ['massapizza'] = {nome = 'Massa de pizza', peso = 1.0},
        ['queijo'] = {nome = 'Queijo', peso = 1.0},
        ['pacotefritas'] = {nome = 'Pacote Fritas', peso = 1.0},
        ['pacotenuggets'] = {nome = 'Pacote Nuggets', peso = 1.0},
        ['pacotecebolas'] = {nome = 'Pacote Cebolas', peso = 1.0},

        -- << ARMAMENTOS >>
        ['makita'] = {nome = 'Makita', peso = 2, type = 'weapon'},
        ['machado'] = {nome = 'Machado', peso = 2.5, type = 'weapon'},
        ['martelo'] = {nome = 'Martelo', peso = 1.2, type = 'weapon'},
        ['imbel'] = {nome = 'Imbel', peso = 7, muni = 'mfuzil', type = 'weapon'},
        ['ak103'] = {nome = 'AK-103', peso = 7, muni = 'mfuzil', type = 'weapon'},
        ['glock'] = {nome = 'Glock', peso = 4, muni = 'mpistola', type = 'weapon'},
        ['cassetete'] = {nome = 'Cassetete', peso = 0.8, type = 'weapon'},
        ['faca'] = {nome = 'Faca', peso = 0.8, type = 'weapon'},
        ['mp5'] = {nome = 'MP5', peso = 5, muni = 'msmg', type = 'weapon'},
        ['minismg'] = {nome = 'CZ VZ61 Skorpion', peso = 5, muni = 'msmg', type = 'weapon'},
        ['microsmg'] = {nome = 'Micro Uzi', peso = 5, muni = 'msmg', type = 'weapon'},
        ['revolver'] = {nome = 'Revolver', peso = 4, muni = 'mpistola', type = 'weapon'},
        ['taurus'] = {nome = 'Taurus', peso = 4, muni = 'mpistola', type = 'weapon'},
        ['hkp7m'] = {nome = 'HK P7M', peso = 4, muni = 'mpistola', type = 'weapon'},
        ['taser'] = {nome = 'Arma Elétrica', peso = 4, type = 'weapon'},
        ['cassetete'] = {nome = 'Cassetete', peso = 1, type = 'weapon'},
        ['soqueira'] = {nome = 'Soco Inglês', peso = 1, type = 'weapon'},

        ['vest'] = {nome = 'Colete', peso = 4},

        -- << ITEMS CASA >>

        ['alianca'] = {nome = 'Aliança', peso = 0.5},
        ['anel'] = {nome = 'Anel', peso = 0.5},
        ['bracelete'] = {nome = 'Bracelete', peso = 0.5},
        ['colar'] = {nome = 'Colar', peso = 0.5},
        ['mouse'] = {nome = 'Mouse', peso = 0.5},
        ['pilhas'] = {nome = 'Pilhas', peso = 0.5},
        ['teclado'] = {nome = 'Teclado', peso = 0.5},
        ['xbox'] = {nome = 'Xbox', peso = 1.5},

        -- << MUNIÇÕES >>
        ['mpistola'] = {nome = 'Munição de Pistola', peso = 0.1},
        ['mfuzil'] = {nome = 'Munição de Fuzil', peso = 0.1},
        ['msmg'] = {nome = 'Munição de SMG', peso = 0.1},
        ['mshotgun'] = {nome = 'Munição de Espingarda', peso = 0.1},
        ['mrifle'] = {nome = 'Munição de Rifle', peso = 0.1},

        -- << ROTAS >>
        ['capsula'] = {nome = 'Capsula Vazia', peso = 0.1},
        ['polvoraa'] = {nome = 'Polvora A', peso = 0.02},
        ['polvorab'] = {nome = 'Polvora B', peso = 0.02},
        ['polvorac'] = {nome = 'Polvora C', peso = 0.02},
        ['polvorad'] = {nome = 'Polvora D', peso = 0.02},

        ['partfuzila1'] = {nome = 'Parte de Fuzil A', peso = 1.2},
        ['partfuzila2'] = {nome = 'Parte de Fuzil A', peso = 1.2},
        ['partfuzila3'] = {nome = 'Parte de Fuzil A', peso = 1.2},

        ['partfuzilb1'] = {nome = 'Parte de Fuzil B', peso = 1.2},
        ['partfuzilb2'] = {nome = 'Parte de Fuzil B', peso = 1.2},
        ['partfuzilb3'] = {nome = 'Parte de Fuzil B', peso = 1.2},

        ['partpistolab1'] = {nome = 'Parte de Pistola A', peso = 1.2},
        ['partpistolab2'] = {nome = 'Parte de Pistola A', peso = 1.2},

        ['partpistolaa1'] = {nome = 'Parte de Pistola B', peso = 1.2},
        ['partpistolaa2'] = {nome = 'Parte de Pistola B', peso = 1.2},

        ['partsmga1'] = {nome = 'Parte de SMG A', peso = 1.2},
        ['partsmga2'] = {nome = 'Parte de SMG A', peso = 1.2},

        ['partsmgb1'] = {nome = 'Parte de SMG B', peso = 1.2},
        ['partsmgb2'] = {nome = 'Parte de SMG B', peso = 1.2},

        ['titanium'] = {nome = 'Titanium', peso = 0.5},
        ['metal'] = {nome = 'Titanium', peso = 0.5},
        ['kevlar'] = {nome = 'Kevlar', peso = 1.2},
        ['ziplock'] = {nome = 'Plástico Zip Lock', peso = 0.5},
        ['aluminio'] = {nome = 'Pedaço de Alumínio', peso = 0.8},

        ['pendrive'] = {nome = 'Pendrive', peso = 0.3},
        ['dinheirosujo'] = {nome = 'Dinheiro Sujo', peso = 0.0},
        ['dinheiro'] = {nome = 'Dinheiro', peso = 0.0, desc="Descrição: Notas de dólares americanos"},

        -- << EMPREGOS >>
        ['tora'] = {nome = 'Tora de Madeira', peso = 3},
        ['picareta'] = {nome = 'Picareta', peso = 3},

        -- << MARIJUANA >>
        ['maconha'] = {nome = 'Baseado', peso = 0.5},
        ['baggie'] = {nome = 'Baggie', peso=0.2},
        ['budmolhado'] = {nome = 'Bud Molhado', peso=0.7},
        ['budseco'] = {nome = 'Bud Seco', peso=0.5},
        ['fertilizante'] = {nome = "Fertilizante", peso=1.0, desc="Ajuda bastante em plantações!"},
        ["regador"] = {nome = "Regador", peso=1.0, desc="É sempre deixar suas plantinhas com água"},
        ["sementeF"] = {nome = "Semente", peso=0.5, desc="Semente de Maconha Feminina"},
        ["sementeM"] = {nome = "Semente", peso=0.5, desc="Semente de Maconha Masculina"},
        ["weedbox"] = {nome = "Caixa Secreta", peso=2.0},


        -- << pescador >>
        ['bacalhau'] = {nome = 'Bacalhau', peso = 0.4},
        ['bagre'] = {nome = 'Bagre', peso = 0.4},
        ['camarao'] = {nome = 'Camarao', peso = 0.4},
        ['cavala'] = {nome = 'Cavala', peso = 0.4},
        ['pacu'] = {nome = 'Pacu', peso = 0.4},
        ['carpa'] = {nome = 'Carpa', peso = 0.4},
        ['tambaqui'] = {nome = 'Tambaqui', peso = 0.4},
        ['tilapia'] = {nome = 'Tilapia', peso = 0.4},
        ['isca'] = {nome = 'Isca', peso = 0.1},
        ['vara'] = {nome = 'Vara de Pescar', peso = 1.7},
        ['licensapescador'] = {nome = 'Licença de Pescador', peso = 0.01, document = true},


        -- minerador
        ['pedra'] = {nome = 'Pedra', peso = 2},
        ['ouro'] = {nome = 'Ouro', peso = 1},
        ['rubi'] = {nome = 'Rubi', peso = 1},
        ['safira'] = {nome = 'Safira', peso = 1},
        ['esmeralda'] = {nome = 'Esmeralda', peso = 1},
        ['turquesa'] = {nome = 'Turquesa', peso = 1},
        ['diamante'] = {nome = 'Diamante', peso = 1},


        -- << UTILITARIOS >>
        ['slots'] = {nome = 'Aumentar slots', peso = 0.4},
        ['mochila'] = {nome = 'Mochila', peso = 0.4},
        ['radio'] = {nome = 'Radio Comunicador', peso = 0.4, type = 'phone'},
        ['celular'] = {nome = 'Celular', peso = 0.3, document = false, type = 'phone'},
        ['laptop'] = {nome = 'Laptop', peso = 1.5, document = false, type = 'phone'},
        ['tablet'] = {nome = 'Tablet', peso = 0.8, document = false, type = 'phone'},
        ['vpn'] = {nome = 'VPN', peso = 0.2, document = false, type = 'phone'},
        ['chavemicha'] = {nome = 'Chave Micha', peso = 0.1},
        ['lockpick'] = {nome = 'Lockpick', peso = 0.1},
        ['lockpickq'] = {nome = 'Lockpick Quebrada', peso = 0.05},
        ['algema'] = {nome = 'Algema', peso = 1},
        ['vaso'] = {nome = 'Vaso', peso = 1},
        ['adrenalina'] = {nome = 'Adrenalina', peso = 0.3},
        ['cordas'] = {nome = 'Corda', peso = 0.3},
        ['gasolina'] = {nome = 'Galão de Gasolina', peso = 2},
        ['camera'] = {nome = 'Camera', peso = 1},
        ['desfibrilador'] = {nome = 'Desfibrilador', peso = 1},
        ['gaze'] = {nome = 'Gaze', peso = 0.1},
        ['chavecarro'] = {nome = 'Chave de Veiculo', peso = 0.1, document = true},
        ['isqueiro'] = {nome = 'Isqueiro', peso = 0.023},
        ['caixacigarro'] = {nome = 'Caixa de Redwood', peso = 0.160},
        ['cigarro'] = {nome = 'Cigarro Redwood', peso = 0.016},


        -- << CAIXAS MISTERIOSAS >>
        ['hbox'] = {nome = 'Caixa de Halloween', peso = 0.1},

        -- << MECANICO >>
        ['kitreparo'] = {nome = 'Kit de Ferramentas', peso = 0.6},
        ['motora'] = {nome = 'Motor de Moto', peso = 0.6},
        ['motorb'] = {nome = 'Motor de Carro', peso = 0.6},
        ['portaa'] = {nome = 'Porta de Carro', peso = 0.6},
        ['turbina'] = {nome = 'Turbina', peso = 2},
        ['pneua'] = {nome = 'Pneu de Moto', peso = 0.6},
        ['pneub'] = {nome = 'Pneu de Carro', peso = 0.6},


        -- << maconha >>
        ['sementemaconha'] = {nome = 'Semente de Maconha', peso = 0.1},
        ['maconha'] = {nome = 'Maconha', peso = 0.1},
        ['baseado'] = {nome = 'Baseado', peso = 0.1},
        ['seda'] = {nome = 'Seda', peso = 0.1},

        -- << CASAS >>
        ['contratoa'] = {nome = 'Contrato de Casa (F-1)', peso = 0.02},
        ['contratob'] = {nome = 'Contrato de Casa (F-2)', peso = 0.02},
        ['contratoc'] = {nome = 'Contrato de Casa (D-1)', peso = 0.02},
        ['contratod'] = {nome = 'Contrato de Casa (D-2)', peso = 0.02},
        ['contratoe'] = {nome = 'Contrato de Casa (C-1)', peso = 0.02},
        ['contratof'] = {nome = 'Contrato de Casa (C-2)', peso = 0.02},
        ['contratog'] = {nome = 'Contrato de Casa (B)', peso = 0.02},
        ['contratoh'] = {nome = 'Contrato de Casa (A)', peso = 0.02},

        -- LIXEIRA --
        ['elastico'] = {nome = 'Elastico', peso = 0.02},
        ['pano'] = {nome = 'Pano', peso = 0.02},
        ['tecido'] = {nome = 'Tecido', peso = 0.02},
        ['jornal'] = {nome = 'Jornal', peso = 0.02},
        ['fita'] = {nome = 'Fita', peso = 0.02},
        ['garrafaq'] = {nome = 'Garrafa Quebrada', peso = 0.02},
        ['corrente'] = {nome = 'Corrente', peso = 0.02},
        

        -- << ROUPAS >>

        ['mascara-1-1'] = {nome = 'Mascara (M/F) 1-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-2-1'] = {nome = 'Mascara (M/F) 2-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-3-1'] = {nome = 'Mascara (M/F) 3-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-4-1'] = {nome = 'Mascara (M/F) 4-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-5-1'] = {nome = 'Mascara (M/F) 5-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-5-2'] = {nome = 'Mascara (M/F) 5-2', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-6-1'] = {nome = 'Mascara (M/F) 6-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-7-1'] = {nome = 'Mascara (M/F) 7-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-7-2'] = {nome = 'Mascara (M/F) 7-2', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-8-1'] = {nome = 'Mascara (M/F) 8-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-9-1'] = {nome = 'Mascara (M/F) 9-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-10-1'] = {nome = 'Mascara (M/F) 10-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-11-1'] = {nome = 'Mascara (M/F) 11-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-11-2'] = {nome = 'Mascara (M/F) 11-2', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-12-1'] = {nome = 'Mascara (M/F) 12-1', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascara-12-2'] = {nome = 'Mascara (M/F) 12-2', peso=0.02, model=7, arg='mascara', style='1', text='1'},
        ['mascarah'] = {nome = 'Mascara Halloween', peso=0.02, model=7, arg='mascara', style='1', text='1'},

        ['acessorios-1-1'] = {nome = 'Corrente (M/F) 1-1', peso=0.02, model=7, arg='acessorios', style='1', text='1'},
        ['acessorios-1-2'] = {nome = 'Corrente (M/F) 1-2', peso=0.02, model=7, arg='acessorios', style='1', text='2'},
        ['acessorios-2-1'] = {nome = 'Corrente (M/F) 2-1', peso=0.02, model=7, arg='acessorios', style='2', text='1'},
        ['acessorios-2-2'] = {nome = 'Corrente (M/F) 2-2', peso=0.02, model=7, arg='acessorios', style='2', text='2'},
        ['acessorios-3-1'] = {nome = 'Corrente (M/F) 3-1', peso=0.02, model=7, arg='acessorios', style='3', text='1'},
        ['acessorios-3-2'] = {nome = 'Corrente (M/F) 3-2', peso=0.02, model=7, arg='acessorios', style='3', text='2'},
        ['acessorios-4-1'] = {nome = 'Corrente (M/F) 4-1', peso=0.02, model=7, arg='acessorios', style='4', text='1'},
        ['acessorios-4-2'] = {nome = 'Corrente (M/F) 4-2', peso=0.02, model=7, arg='acessorios', style='4', text='2'},

        ['bone-1-1'] = {nome = 'Bone (M/F) 1-1', peso=0.02, model=7, arg='bone', style='1', text='1'},
        ['bone-1-2'] = {nome = 'Bone (M/F) 1-2', peso=0.02, model=7, arg='bone', style='1', text='2'},
        ['bone-1-3'] = {nome = 'Bone (M/F) 1-3', peso=0.02, model=7, arg='bone', style='1', text='3'},
        ['bone-1-4'] = {nome = 'Bone (M/F) 1-4', peso=0.02, model=7, arg='bone', style='1', text='4'},
        ['bone-1-5'] = {nome = 'Bone (M/F) 1-5', peso=0.02, model=7, arg='bone', style='1', text='5'},
        ['bone-1-6'] = {nome = 'Bone (M/F) 1-6', peso=0.02, model=7, arg='bone', style='1', text='6'},
        ['bone-1-7'] = {nome = 'Bone (M/F) 1-7', peso=0.02, model=7, arg='bone', style='1', text='7'},
        ['bone-1-8'] = {nome = 'Bone (M/F) 1-8', peso=0.02, model=7, arg='bone', style='1', text='8'},
        ['bone-1-9'] = {nome = 'Bone (M/F) 1-9', peso=0.02, model=7, arg='bone', style='1', text='9'},
        ['bone-1-10'] = {nome = 'Bone (M/F) 1-10', peso=0.02, model=7, arg='bone', style='1', text='10'},
        ['bone-1-11'] = {nome = 'Bone (M/F) 1-11', peso=0.02, model=7, arg='bone', style='1', text='11'},
        ['bone-1-12'] = {nome = 'Bone (M/F) 1-12', peso=0.02, model=7, arg='bone', style='1', text='12'},
        ['bone-1-13'] = {nome = 'Bone (M/F) 1-13', peso=0.02, model=7, arg='bone', style='1', text='13'},
        ['bone-1-14'] = {nome = 'Bone (M/F) 1-14', peso=0.02, model=7, arg='bone', style='1', text='14'},
        ['bone-1-15'] = {nome = 'Bone (M/F) 1-15', peso=0.02, model=7, arg='bone', style='1', text='15'},
        ['bone-1-16'] = {nome = 'Bone (M/F) 1-16', peso=0.02, model=7, arg='bone', style='1', text='16'},
        ['bone-1-17'] = {nome = 'Bone (M/F) 1-17', peso=0.02, model=7, arg='bone', style='1', text='17'},
        ['bone-1-18'] = {nome = 'Bone (M/F) 1-18', peso=0.02, model=7, arg='bone', style='1', text='18'},
        ['bone-1-19'] = {nome = 'Bone (M/F) 1-19', peso=0.02, model=7, arg='bone', style='1', text='19'},
        ['bone-1-20'] = {nome = 'Bone (M/F) 1-20', peso=0.02, model=7, arg='bone', style='1', text='20'},

        ['bone-2-1'] = {nome = 'Bone (M/F) 2-1', peso=0.02, model=7, arg='bone', style='2', text='1'},
        ['bone-2-2'] = {nome = 'Bone (M/F) 2-2', peso=0.02, model=7, arg='bone', style='2', text='2'},
        ['bone-2-3'] = {nome = 'Bone (M/F) 2-3', peso=0.02, model=7, arg='bone', style='2', text='3'},
        ['bone-2-4'] = {nome = 'Bone (M/F) 2-4', peso=0.02, model=7, arg='bone', style='2', text='4'},
        ['bone-2-5'] = {nome = 'Bone (M/F) 2-5', peso=0.02, model=7, arg='bone', style='2', text='5'},
        ['bone-2-6'] = {nome = 'Bone (M/F) 2-6', peso=0.02, model=7, arg='bone', style='2', text='6'},
        ['bone-2-7'] = {nome = 'Bone (M/F) 2-7', peso=0.02, model=7, arg='bone', style='2', text='7'},
        ['bone-2-8'] = {nome = 'Bone (M/F) 2-8', peso=0.02, model=7, arg='bone', style='2', text='8'},
        ['bone-2-9'] = {nome = 'Bone (M/F) 2-9', peso=0.02, model=7, arg='bone', style='2', text='9'},
        ['bone-2-10'] = {nome = 'Bone (M/F) 2-10', peso=0.02, model=7, arg='bone', style='2', text='10'},
        ['bone-2-11'] = {nome = 'Bone (M/F) 2-11', peso=0.02, model=7, arg='bone', style='2', text='11'},
        ['bone-2-12'] = {nome = 'Bone (M/F) 2-12', peso=0.02, model=7, arg='bone', style='2', text='12'},
        ['bone-2-13'] = {nome = 'Bone (M/F) 2-13', peso=0.02, model=7, arg='bone', style='2', text='13'},
        ['bone-2-14'] = {nome = 'Bone (M/F) 2-14', peso=0.02, model=7, arg='bone', style='2', text='14'},
        ['bone-2-15'] = {nome = 'Bone (M/F) 2-15', peso=0.02, model=7, arg='bone', style='2', text='15'},
        ['bone-2-16'] = {nome = 'Bone (M/F) 2-16', peso=0.02, model=7, arg='bone', style='2', text='16'},
        ['bone-2-17'] = {nome = 'Bone (M/F) 2-17', peso=0.02, model=7, arg='bone', style='2', text='17'},
        ['bone-2-18'] = {nome = 'Bone (M/F) 2-18', peso=0.02, model=7, arg='bone', style='2', text='18'},
        ['bone-2-19'] = {nome = 'Bone (M/F) 2-19', peso=0.02, model=7, arg='bone', style='2', text='19'},
        ['bone-2-20'] = {nome = 'Bone (M/F) 2-20', peso=0.02, model=7, arg='bone', style='2', text='20'},

        --< BERMUDAS MASCULINAS >>

        ['bermuda-3-1'] = {nome = 'Bermuda (M) 1-1', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '1'},
        ['bermuda-3-2'] = {nome = 'Bermuda (M) 1-2', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '2'},
        ['bermuda-3-3'] = {nome = 'Bermuda (M) 1-3', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '3'},
        ['bermuda-3-4'] = {nome = 'Bermuda (M) 1-4', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '4'},
        ['bermuda-3-5'] = {nome = 'Bermuda (M) 1-5', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '5'},
        ['bermuda-3-6'] = {nome = 'Bermuda (M) 1-6', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '6'},
        ['bermuda-3-7'] = {nome = 'Bermuda (M) 1-7', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '7'},
        ['bermuda-3-8'] = {nome = 'Bermuda (M) 1-8', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '8'},
        ['bermuda-3-9'] = {nome = 'Bermuda (M) 1-9', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '9'},
        ['bermuda-3-10'] = {nome = 'Bermuda (M) 1-10', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '10'},
        ['bermuda-3-11'] = {nome = 'Bermuda (M) 1-11', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '11'},
        ['bermuda-3-12'] = {nome = 'Bermuda (M) 1-12', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '12'},
        ['bermuda-3-13'] = {nome = 'Bermuda (M) 1-13', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '13'},
        ['bermuda-3-14'] = {nome = 'Bermuda (M) 1-14', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '14'},
        ['bermuda-3-15'] = {nome = 'Bermuda (M) 1-15', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '15'},
        ['bermuda-3-16'] = {nome = 'Bermuda (M) 1-16', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '16'},
        ['bermuda-3-17'] = {nome = 'Bermuda (M) 1-17', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '17'},
        ['bermuda-3-18'] = {nome = 'Bermuda (M) 1-18', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '18'},
        ['bermuda-3-19'] = {nome = 'Bermuda (M) 1-19', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '19'},
        ['bermuda-3-20'] = {nome = 'Bermuda (M) 1-20', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '20'},
        ['bermuda-3-21'] = {nome = 'Bermuda (M) 1-21', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '21'},
        ['bermuda-3-22'] = {nome = 'Bermuda (M) 1-22', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '22'},
        ['bermuda-3-23'] = {nome = 'Bermuda (M) 1-23', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '23'},
        ['bermuda-3-24'] = {nome = 'Bermuda (M) 1-24', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '24'},
        ['bermuda-3-25'] = {nome = 'Bermuda (M) 1-25', peso = 0.02, model = 7, arg = 'calca', style = '3', text = '25'},

        --< CAMISAS MASCULINAS >

        ['camisa-1-1'] = {nome = 'Camisa (M) 1-1', peso=0.02, model=7, arg='camisa', style='1', text='1'},
        ['camisa-1-2'] = {nome = 'Camisa (M) 1-2', peso=0.02, model=7, arg='camisa', style='1', text='2'},
        ['camisa-1-3'] = {nome = 'Camisa (M) 1-3', peso=0.02, model=7, arg='camisa', style='1', text='3'},
        ['camisa-1-4'] = {nome = 'Camisa (M) 1-4', peso=0.02, model=7, arg='camisa', style='1', text='4'},
        ['camisa-1-5'] = {nome = 'Camisa (M) 1-5', peso=0.02, model=7, arg='camisa', style='1', text='5'},
        ['camisa-1-6'] = {nome = 'Camisa (M) 1-6', peso=0.02, model=7, arg='camisa', style='1', text='6'},
        ['camisa-1-7'] = {nome = 'Camisa (M) 1-7', peso=0.02, model=7, arg='camisa', style='1', text='7'},
        ['camisa-1-8'] = {nome = 'Camisa (M) 1-8', peso=0.02, model=7, arg='camisa', style='1', text='8'},
        ['camisa-1-9'] = {nome = 'Camisa (M) 1-9', peso=0.02, model=7, arg='camisa', style='1', text='9'},
        ['camisa-1-10'] = {nome = 'Camisa (M) 1-10', peso=0.02, model=7, arg='camisa', style='1', text='10'},
        ['camisa-1-11'] = {nome = 'Camisa (M) 1-11', peso=0.02, model=7, arg='camisa', style='1', text='11'},

        ['camisa-2-1'] = {nome = 'Camisa (M) 2-1', peso=0.02, model=7, arg='camisa', style='2', text='1'},
        ['camisa-2-2'] = {nome = 'Camisa (M) 2-2', peso=0.02, model=7, arg='camisa', style='2', text='2'},
        ['camisa-2-3'] = {nome = 'Camisa (M) 2-3', peso=0.02, model=7, arg='camisa', style='2', text='3'},
        ['camisa-2-4'] = {nome = 'Camisa (M) 2-4', peso=0.02, model=7, arg='camisa', style='2', text='4'},
        ['camisa-2-5'] = {nome = 'Camisa (M) 2-5', peso=0.02, model=7, arg='camisa', style='2', text='5'},
        ['camisa-2-6'] = {nome = 'Camisa (M) 2-6', peso=0.02, model=7, arg='camisa', style='2', text='6'},
        ['camisa-2-7'] = {nome = 'Camisa (M) 2-7', peso=0.02, model=7, arg='camisa', style='2', text='7'},
        ['camisa-2-8'] = {nome = 'Camisa (M) 2-8', peso=0.02, model=7, arg='camisa', style='2', text='8'},
        ['camisa-2-9'] = {nome = 'Camisa (M) 2-9', peso=0.02, model=7, arg='camisa', style='2', text='9'},
        ['camisa-2-10'] = {nome = 'Camisa (M) 2-10', peso=0.02, model=7, arg='camisa', style='2', text='10'},
        ['camisa-2-11'] = {nome = 'Camisa (M) 2-11', peso=0.02, model=7, arg='camisa', style='2', text='11'},
        ['camisa-2-12'] = {nome = 'Camisa (M) 2-12', peso=0.02, model=7, arg='camisa', style='2', text='12'},
        ['camisa-2-13'] = {nome = 'Camisa (M) 2-13', peso=0.02, model=7, arg='camisa', style='2', text='13'},
        ['camisa-2-14'] = {nome = 'Camisa (M) 2-14', peso=0.02, model=7, arg='camisa', style='2', text='14'},
        ['camisa-2-15'] = {nome = 'Camisa (M) 2-15', peso=0.02, model=7, arg='camisa', style='2', text='15'},
        ['camisa-2-16'] = {nome = 'Camisa (M) 2-16', peso=0.02, model=7, arg='camisa', style='2', text='16'},
        ['camisa-2-17'] = {nome = 'Camisa (M) 2-17', peso=0.02, model=7, arg='camisa', style='2', text='17'},
        ['camisa-2-18'] = {nome = 'Camisa (M) 2-18', peso=0.02, model=7, arg='camisa', style='2', text='18'},
        ['camisa-2-19'] = {nome = 'Camisa (M) 2-19', peso=0.02, model=7, arg='camisa', style='2', text='19'},
        ['camisa-2-20'] = {nome = 'Camisa (M) 2-20', peso=0.02, model=7, arg='camisa', style='2', text='20'},
        ['camisa-2-21'] = {nome = 'Camisa (M) 2-21', peso=0.02, model=7, arg='camisa', style='2', text='21'},
        ['camisa-2-22'] = {nome = 'Camisa (M) 2-22', peso=0.02, model=7, arg='camisa', style='2', text='22'},
        ['camisa-2-23'] = {nome = 'Camisa (M) 2-23', peso=0.02, model=7, arg='camisa', style='2', text='23'},
        ['camisa-2-24'] = {nome = 'Camisa (M) 2-24', peso=0.02, model=7, arg='camisa', style='2', text='24'},
        ['camisa-2-25'] = {nome = 'Camisa (M) 2-25', peso=0.02, model=7, arg='camisa', style='2', text='25'},
        ['camisa-2-26'] = {nome = 'Camisa (M) 2-26', peso=0.02, model=7, arg='camisa', style='2', text='26'},
        ['camisa-2-27'] = {nome = 'Camisa (M) 2-27', peso=0.02, model=7, arg='camisa', style='2', text='27'},
        ['camisa-2-28'] = {nome = 'Camisa (M) 2-28', peso=0.02, model=7, arg='camisa', style='2', text='28'},
        ['camisa-2-29'] = {nome = 'Camisa (M) 2-29', peso=0.02, model=7, arg='camisa', style='2', text='29'},
        ['camisa-2-30'] = {nome = 'Camisa (M) 2-30', peso=0.02, model=7, arg='camisa', style='2', text='30'},
        ['camisa-2-31'] = {nome = 'Camisa (M) 2-31', peso=0.02, model=7, arg='camisa', style='2', text='31'},
        ['camisa-2-32'] = {nome = 'Camisa (M) 2-32', peso=0.02, model=7, arg='camisa', style='2', text='32'},
        ['camisa-2-33'] = {nome = 'Camisa (M) 2-33', peso=0.02, model=7, arg='camisa', style='2', text='33'},
        ['camisa-2-34'] = {nome = 'Camisa (M) 2-34', peso=0.02, model=7, arg='camisa', style='2', text='34'},
        ['camisa-2-35'] = {nome = 'Camisa (M) 2-35', peso=0.02, model=7, arg='camisa', style='2', text='35'},
        ['camisa-2-36'] = {nome = 'Camisa (M) 2-36', peso=0.02, model=7, arg='camisa', style='2', text='36'},
        ['camisa-2-37'] = {nome = 'Camisa (M) 2-37', peso=0.02, model=7, arg='camisa', style='2', text='37'},
        ['camisa-2-38'] = {nome = 'Camisa (M) 2-38', peso=0.02, model=7, arg='camisa', style='2', text='38'},
        ['camisa-2-39'] = {nome = 'Camisa (M) 2-39', peso=0.02, model=7, arg='camisa', style='2', text='39'},
        ['camisa-2-40'] = {nome = 'Camisa (M) 2-40', peso=0.02, model=7, arg='camisa', style='2', text='40'},
        ['camisa-2-41'] = {nome = 'Camisa (M) 2-41', peso=0.02, model=7, arg='camisa', style='2', text='41'},
        ['camisa-2-42'] = {nome = 'Camisa (M) 2-42', peso=0.02, model=7, arg='camisa', style='2', text='42'},
        ['camisa-2-43'] = {nome = 'Camisa (M) 2-43', peso=0.02, model=7, arg='camisa', style='2', text='43'},
        ['camisa-2-44'] = {nome = 'Camisa (M) 2-44', peso=0.02, model=7, arg='camisa', style='2', text='44'},
        ['camisa-2-45'] = {nome = 'Camisa (M) 2-45', peso=0.02, model=7, arg='camisa', style='2', text='45'},
        ['camisa-2-46'] = {nome = 'Camisa (M) 2-46', peso=0.02, model=7, arg='camisa', style='2', text='46'},
        ['camisa-2-47'] = {nome = 'Camisa (M) 2-47', peso=0.02, model=7, arg='camisa', style='2', text='47'},
        ['camisa-2-48'] = {nome = 'Camisa (M) 2-48', peso=0.02, model=7, arg='camisa', style='2', text='48'},
        ['camisa-2-49'] = {nome = 'Camisa (M) 2-49', peso=0.02, model=7, arg='camisa', style='2', text='49'},
        ['camisa-2-50'] = {nome = 'Camisa (M) 2-50', peso=0.02, model=7, arg='camisa', style='2', text='50'},
        ['camisa-2-51'] = {nome = 'Camisa (M) 2-51', peso=0.02, model=7, arg='camisa', style='2', text='51'},
        ['camisa-2-52'] = {nome = 'Camisa (M) 2-52', peso=0.02, model=7, arg='camisa', style='2', text='52'},
        ['camisa-2-53'] = {nome = 'Camisa (M) 2-53', peso=0.02, model=7, arg='camisa', style='2', text='53'},
        ['camisa-2-54'] = {nome = 'Camisa (M) 2-54', peso=0.02, model=7, arg='camisa', style='2', text='54'},
        ['camisa-2-55'] = {nome = 'Camisa (M) 2-55', peso=0.02, model=7, arg='camisa', style='2', text='55'},
        ['camisa-2-56'] = {nome = 'Camisa (M) 2-56', peso=0.02, model=7, arg='camisa', style='2', text='56'},
        ['camisa-2-57'] = {nome = 'Camisa (M) 2-57', peso=0.02, model=7, arg='camisa', style='2', text='57'},
        ['camisa-2-58'] = {nome = 'Camisa (M) 2-58', peso=0.02, model=7, arg='camisa', style='2', text='58'},
        ['camisa-2-59'] = {nome = 'Camisa (M) 2-59', peso=0.02, model=7, arg='camisa', style='2', text='59'},
        ['camisa-2-60'] = {nome = 'Camisa (M) 2-60', peso=0.02, model=7, arg='camisa', style='2', text='60'},
        ['camisa-2-61'] = {nome = 'Camisa (M) 2-61', peso=0.02, model=7, arg='camisa', style='2', text='61'},
        ['camisa-2-62'] = {nome = 'Camisa (M) 2-62', peso=0.02, model=7, arg='camisa', style='2', text='62'},
        ['camisa-2-63'] = {nome = 'Camisa (M) 2-63', peso=0.02, model=7, arg='camisa', style='2', text='63'},
        ['camisa-2-64'] = {nome = 'Camisa (M) 2-64', peso=0.02, model=7, arg='camisa', style='2', text='64'},
        ['camisa-2-65'] = {nome = 'Camisa (M) 2-65', peso=0.02, model=7, arg='camisa', style='2', text='65'},
        ['camisa-2-66'] = {nome = 'Camisa (M) 2-66', peso=0.02, model=7, arg='camisa', style='2', text='66'},
        ['camisa-2-67'] = {nome = 'Camisa (M) 2-67', peso=0.02, model=7, arg='camisa', style='2', text='67'},
        ['camisa-2-68'] = {nome = 'Camisa (M) 2-68', peso=0.02, model=7, arg='camisa', style='2', text='68'},
        ['camisa-2-69'] = {nome = 'Camisa (M) 2-69', peso=0.02, model=7, arg='camisa', style='2', text='69'},
        ['camisa-2-70'] = {nome = 'Camisa (M) 2-70', peso=0.02, model=7, arg='camisa', style='2', text='70'},
        ['camisa-2-71'] = {nome = 'Camisa (M) 2-71', peso=0.02, model=7, arg='camisa', style='2', text='71'},
        ['camisa-2-72'] = {nome = 'Camisa (M) 2-72', peso=0.02, model=7, arg='camisa', style='2', text='72'},
        ['camisa-2-73'] = {nome = 'Camisa (M) 2-73', peso=0.02, model=7, arg='camisa', style='2', text='73'},
        ['camisa-2-74'] = {nome = 'Camisa (M) 2-74', peso=0.02, model=7, arg='camisa', style='2', text='74'},
        ['camisa-2-75'] = {nome = 'Camisa (M) 2-75', peso=0.02, model=7, arg='camisa', style='2', text='75'},
        ['camisa-2-76'] = {nome = 'Camisa (M) 2-76', peso=0.02, model=7, arg='camisa', style='2', text='76'},
        ['camisa-2-77'] = {nome = 'Camisa (M) 2-77', peso=0.02, model=7, arg='camisa', style='2', text='77'},
        ['camisa-2-78'] = {nome = 'Camisa (M) 2-78', peso=0.02, model=7, arg='camisa', style='2', text='78'},
        ['camisa-2-79'] = {nome = 'Camisa (M) 2-79', peso=0.02, model=7, arg='camisa', style='2', text='79'},
        ['camisa-2-80'] = {nome = 'Camisa (M) 2-80', peso=0.02, model=7, arg='camisa', style='2', text='80'},
        ['camisa-2-81'] = {nome = 'Camisa (M) 2-81', peso=0.02, model=7, arg='camisa', style='2', text='81'},
        ['camisa-2-82'] = {nome = 'Camisa (M) 2-82', peso=0.02, model=7, arg='camisa', style='2', text='82'},
        ['camisa-2-83'] = {nome = 'Camisa (M) 2-83', peso=0.02, model=7, arg='camisa', style='2', text='83'},
        ['camisa-2-84'] = {nome = 'Camisa (M) 2-84', peso=0.02, model=7, arg='camisa', style='2', text='84'},

        ['camisa-3-1'] = {nome = 'Camisa (M) 3-1', peso=0.02, model=7, arg='camisa', style='3', text='1'},
        ['camisa-3-2'] = {nome = 'Camisa (M) 3-2', peso=0.02, model=7, arg='camisa', style='3', text='2'},
        ['camisa-3-3'] = {nome = 'Camisa (M) 3-3', peso=0.02, model=7, arg='camisa', style='3', text='3'},
        ['camisa-3-4'] = {nome = 'Camisa (M) 3-4', peso=0.02, model=7, arg='camisa', style='3', text='4'},
        ['camisa-3-5'] = {nome = 'Camisa (M) 3-5', peso=0.02, model=7, arg='camisa', style='3', text='5'},
        ['camisa-3-6'] = {nome = 'Camisa (M) 3-6', peso=0.02, model=7, arg='camisa', style='3', text='6'},
        ['camisa-3-7'] = {nome = 'Camisa (M) 3-7', peso=0.02, model=7, arg='camisa', style='3', text='7'},
        ['camisa-3-8'] = {nome = 'Camisa (M) 3-8', peso=0.02, model=7, arg='camisa', style='3', text='8'},

        ['camisa-4-1'] = {nome = 'Camisa (M) 4-1', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '1'},
        ['camisa-4-2'] = {nome = 'Camisa (M) 4-2', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '2'},
        ['camisa-4-3'] = {nome = 'Camisa (M) 4-3', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '3'},
        ['camisa-4-4'] = {nome = 'Camisa (M) 4-4', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '4'},
        ['camisa-4-5'] = {nome = 'Camisa (M) 4-5', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '5'},
        ['camisa-4-6'] = {nome = 'Camisa (M) 4-6', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '6'},
        ['camisa-4-7'] = {nome = 'Camisa (M) 4-7', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '7'},
        ['camisa-4-8'] = {nome = 'Camisa (M) 4-8', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '8'},
        ['camisa-4-9'] = {nome = 'Camisa (M) 4-9', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '9'},
        ['camisa-4-10'] = {nome = 'Camisa (M) 4-10', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '10'},
        ['camisa-4-11'] = {nome = 'Camisa (M) 4-11', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '11'},
        ['camisa-4-12'] = {nome = 'Camisa (M) 4-12', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '12'},
        ['camisa-4-13'] = {nome = 'Camisa (M) 4-13', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '13'},
        ['camisa-4-14'] = {nome = 'Camisa (M) 4-14', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '14'},
        ['camisa-4-15'] = {nome = 'Camisa (M) 4-15', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '15'},
        ['camisa-4-16'] = {nome = 'Camisa (M) 4-16', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '16'},
        ['camisa-4-17'] = {nome = 'Camisa (M) 4-17', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '17'},
        ['camisa-4-18'] = {nome = 'Camisa (M) 4-18', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '18'},
        ['camisa-4-19'] = {nome = 'Camisa (M) 4-19', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '19'},
        ['camisa-4-20'] = {nome = 'Camisa (M) 4-20', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '20'},
        ['camisa-4-21'] = {nome = 'Camisa (M) 4-21', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '21'},
        ['camisa-4-22'] = {nome = 'Camisa (M) 4-22', peso = 0.02, model = 7, arg = 'camisa', style = '4', text = '22'},

        ['camisa-5-1'] = {nome = 'Camisa (M) 5-1', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '1'},
        ['camisa-5-2'] = {nome = 'Camisa (M) 5-2', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '2'},
        ['camisa-5-3'] = {nome = 'Camisa (M) 5-3', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '3'},
        ['camisa-5-4'] = {nome = 'Camisa (M) 5-4', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '4'},
        ['camisa-5-5'] = {nome = 'Camisa (M) 5-5', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '5'},
        ['camisa-5-6'] = {nome = 'Camisa (M) 5-6', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '6'},
        ['camisa-5-7'] = {nome = 'Camisa (M) 5-7', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '7'},
        ['camisa-5-8'] = {nome = 'Camisa (M) 5-8', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '8'},
        ['camisa-5-9'] = {nome = 'Camisa (M) 5-9', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '9'},
        ['camisa-5-10'] = {nome = 'Camisa (M) 5-10', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '10'},
        ['camisa-5-11'] = {nome = 'Camisa (M) 5-11', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '11'},
        ['camisa-5-12'] = {nome = 'Camisa (M) 5-12', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '12'},
        ['camisa-5-13'] = {nome = 'Camisa (M) 5-13', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '13'},
        ['camisa-5-14'] = {nome = 'Camisa (M) 5-14', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '14'},
        ['camisa-5-15'] = {nome = 'Camisa (M) 5-15', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '15'},
        ['camisa-5-16'] = {nome = 'Camisa (M) 5-16', peso = 0.02, model = 7, arg = 'camisa', style = '5', text = '16'},

        ['camisa-6-1'] = {nome = 'Camisa (M) 6-1', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '1'},
        ['camisa-6-2'] = {nome = 'Camisa (M) 6-2', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '2'},
        ['camisa-6-3'] = {nome = 'Camisa (M) 6-3', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '3'},
        ['camisa-6-4'] = {nome = 'Camisa (M) 6-4', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '4'},
        ['camisa-6-5'] = {nome = 'Camisa (M) 6-5', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '5'},
        ['camisa-6-6'] = {nome = 'Camisa (M) 6-6', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '6'},
        ['camisa-6-7'] = {nome = 'Camisa (M) 6-7', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '7'},
        ['camisa-6-8'] = {nome = 'Camisa (M) 6-8', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '8'},
        ['camisa-6-9'] = {nome = 'Camisa (M) 6-9', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '9'},
        ['camisa-6-10'] = {nome = 'Camisa (M) 6-10', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '10'},
        ['camisa-6-11'] = {nome = 'Camisa (M) 6-11', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '11'},
        ['camisa-6-12'] = {nome = 'Camisa (M) 6-12', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '12'},
        ['camisa-6-13'] = {nome = 'Camisa (M) 6-13', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '13'},
        ['camisa-6-14'] = {nome = 'Camisa (M) 6-14', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '14'},
        ['camisa-6-15'] = {nome = 'Camisa (M) 6-15', peso = 0.02, model = 7, arg = 'camisa', style = '6', text = '15'},

        ['camisa-7-1'] = {nome = 'Camisa (M) 7-1', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '1'},
        ['camisa-7-2'] = {nome = 'Camisa (M) 7-2', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '2'},
        ['camisa-7-3'] = {nome = 'Camisa (M) 7-3', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '3'},
        ['camisa-7-4'] = {nome = 'Camisa (M) 7-4', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '4'},
        ['camisa-7-5'] = {nome = 'Camisa (M) 7-5', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '5'},
        ['camisa-7-6'] = {nome = 'Camisa (M) 7-6', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '6'},
        ['camisa-7-7'] = {nome = 'Camisa (M) 7-7', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '7'},
        ['camisa-7-8'] = {nome = 'Camisa (M) 7-8', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '8'},
        ['camisa-7-9'] = {nome = 'Camisa (M) 7-9', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '9'},
        ['camisa-7-10'] = {nome = 'Camisa (M) 7-10', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '10'},
        ['camisa-7-11'] = {nome = 'Camisa (M) 7-11', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '11'},
        ['camisa-7-12'] = {nome = 'Camisa (M) 7-12', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '12'},
        ['camisa-7-13'] = {nome = 'Camisa (M) 7-13', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '13'},
        ['camisa-7-14'] = {nome = 'Camisa (M) 7-14', peso = 0.02, model = 7, arg = 'camisa', style = '7', text = '14'},

        ['camisa-8-1'] = {nome = 'Camisa (M) 8-1', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '1'},
        ['camisa-8-2'] = {nome = 'Camisa (M) 8-2', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '2'},
        ['camisa-8-3'] = {nome = 'Camisa (M) 8-3', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '3'},
        ['camisa-8-8'] = {nome = 'Camisa (M) 8-4', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '4'},
        ['camisa-8-5'] = {nome = 'Camisa (M) 8-5', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '5'},
        ['camisa-8-6'] = {nome = 'Camisa (M) 8-6', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '6'},
        ['camisa-8-7'] = {nome = 'Camisa (M) 8-7', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '7'},
        ['camisa-8-8'] = {nome = 'Camisa (M) 8-8', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '8'},
        ['camisa-8-9'] = {nome = 'Camisa (M) 8-9', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '9'},
        ['camisa-8-10'] = {nome = 'Camisa (M) 8-10', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '10'},
        ['camisa-8-11'] = {nome = 'Camisa (M) 8-11', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '11'},
        ['camisa-8-12'] = {nome = 'Camisa (M) 8-12', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '12'},
        ['camisa-8-13'] = {nome = 'Camisa (M) 8-13', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '13'},
        ['camisa-8-14'] = {nome = 'Camisa (M) 8-14', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '14'},
        ['camisa-8-15'] = {nome = 'Camisa (M) 8-15', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '15'},
        ['camisa-8-16'] = {nome = 'Camisa (M) 8-16', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '16'},
        ['camisa-8-17'] = {nome = 'Camisa (M) 8-17', peso = 0.02, model = 7, arg = 'camisa', style = '8', text = '17'},

        -- << CALÇA >>

        ['calca-1-1'] = {nome = 'Calça (M) 1-1', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '1'},
        ['calca-1-2'] = {nome = 'Calça (M) 1-2', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '2'},
        ['calca-1-3'] = {nome = 'Calça (M) 1-3', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '3'},
        ['calca-1-4'] = {nome = 'Calça (M) 1-4', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '4'},
        ['calca-1-5'] = {nome = 'Calça (M) 1-5', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '5'},
        ['calca-1-6'] = {nome = 'Calça (M) 1-6', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '6'},
        ['calca-1-7'] = {nome = 'Calça (M) 1-7', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '7'},
        ['calca-1-8'] = {nome = 'Calça (M) 1-8', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '8'},
        ['calca-1-9'] = {nome = 'Calça (M) 1-9', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '9'},
        ['calca-1-10'] = {nome = 'Calça (M) 1-10', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '10'},
        ['calca-1-11'] = {nome = 'Calça (M) 1-11', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '11'},
        ['calca-1-12'] = {nome = 'Calça (M) 1-12', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '12'},
        ['calca-1-13'] = {nome = 'Calça (M) 1-13', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '13'},
        ['calca-1-14'] = {nome = 'Calça (M) 1-14', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '14'},
        ['calca-1-15'] = {nome = 'Calça (M) 1-15', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '15'},
        ['calca-1-16'] = {nome = 'Calça (M) 1-16', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '16'},
        ['calca-1-17'] = {nome = 'Calça (M) 1-17', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '17'},
        ['calca-1-18'] = {nome = 'Calça (M) 1-18', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '18'},
        ['calca-1-19'] = {nome = 'Calça (M) 1-19', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '19'},
        ['calca-1-20'] = {nome = 'Calça (M) 1-20', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '20'},
        ['calca-1-21'] = {nome = 'Calça (M) 1-21', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '21'},
        ['calca-1-22'] = {nome = 'Calça (M) 1-22', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '22'},
        ['calca-1-23'] = {nome = 'Calça (M) 1-23', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '23'},
        ['calca-1-24'] = {nome = 'Calça (M) 1-24', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '24'},
        ['calca-1-25'] = {nome = 'Calça (M) 1-25', peso = 0.02, model = 7, arg = 'calca', style = '1', text = '25'},

        ['calca-2-1'] = {nome = 'Calça (M) 2-1', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '1'},
        ['calca-2-2'] = {nome = 'Calça (M) 2-2', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '2'},
        ['calca-2-3'] = {nome = 'Calça (M) 2-3', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '3'},
        ['calca-2-4'] = {nome = 'Calça (M) 2-4', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '4'},
        ['calca-2-5'] = {nome = 'Calça (M) 2-5', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '5'},
        ['calca-2-6'] = {nome = 'Calça (M) 2-6', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '6'},
        ['calca-2-7'] = {nome = 'Calça (M) 2-7', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '7'},
        ['calca-2-8'] = {nome = 'Calça (M) 2-8', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '8'},
        ['calca-2-9'] = {nome = 'Calça (M) 2-9', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '9'},
        ['calca-2-10'] = {nome = 'Calça (M) 2-10', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '10'},
        ['calca-2-11'] = {nome = 'Calça (M) 2-11', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '11'},
        ['calca-2-12'] = {nome = 'Calça (M) 2-12', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '12'},
        ['calca-2-13'] = {nome = 'Calça (M) 2-13', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '13'},
        ['calca-2-14'] = {nome = 'Calça (M) 2-14', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '14'},
        ['calca-2-15'] = {nome = 'Calça (M) 2-15', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '15'},
        ['calca-2-16'] = {nome = 'Calça (M) 2-16', peso = 0.02, model = 7, arg = 'calca', style = '2', text = '16'},

        ['calca-5-1'] = {nome = 'Calça (M) 5-1', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '1'},
        ['calca-5-2'] = {nome = 'Calça (M) 5-2', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '2'},
        ['calca-5-3'] = {nome = 'Calça (M) 5-3', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '3'},
        ['calca-5-4'] = {nome = 'Calça (M) 5-4', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '4'},
        ['calca-5-5'] = {nome = 'Calça (M) 5-5', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '5'},
        ['calca-5-6'] = {nome = 'Calça (M) 5-6', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '6'},
        ['calca-5-7'] = {nome = 'Calça (M) 5-7', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '7'},
        ['calca-5-8'] = {nome = 'Calça (M) 5-8', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '8'},
        ['calca-5-9'] = {nome = 'Calça (M) 5-9', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '9'},
        ['calca-5-10'] = {nome = 'Calça (M) 5-10', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '10'},
        ['calca-5-11'] = {nome = 'Calça (M) 5-11', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '11'},
        ['calca-5-12'] = {nome = 'Calça (M) 5-12', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '12'},
        ['calca-5-13'] = {nome = 'Calça (M) 5-13', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '13'},
        ['calca-5-14'] = {nome = 'Calça (M) 5-14', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '14'},
        ['calca-5-15'] = {nome = 'Calça (M) 5-15', peso = 0.02, model = 7, arg = 'calca', style = '5', text = '15'},

        ['calca-7-1'] = {nome = 'Calça (M) 7-1', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '1'},
        ['calca-7-2'] = {nome = 'Calça (M) 7-2', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '2'},
        ['calca-7-3'] = {nome = 'Calça (M) 7-3', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '3'},
        ['calca-7-4'] = {nome = 'Calça (M) 7-4', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '4'},
        ['calca-7-7'] = {nome = 'Calça (M) 7-7', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '5'},
        ['calca-7-6'] = {nome = 'Calça (M) 7-6', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '6'},
        ['calca-7-7'] = {nome = 'Calça (M) 7-7', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '7'},
        ['calca-7-8'] = {nome = 'Calça (M) 7-8', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '8'},
        ['calca-7-9'] = {nome = 'Calça (M) 7-9', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '9'},
        ['calca-7-10'] = {nome = 'Calça (M) 7-10', peso = 0.02, model = 7, arg = 'calca', style = '7', text = '10'},

        ['oculos-1-1'] = {nome = 'Juliete (M/F) 1-1', peso=0.02, model=7, arg='oculos', style='1', text='1'},
        ['oculos-1-2'] = {nome = 'Juliete (M/F) 1-2', peso=0.02, model=7, arg='oculos', style='1', text='2'},
        ['oculos-1-3'] = {nome = 'Juliete (M/F) 1-3', peso=0.02, model=7, arg='oculos', style='1', text='3'},
        ['oculos-1-4'] = {nome = 'Juliete (M/F) 1-4', peso=0.02, model=7, arg='oculos', style='1', text='4'},
        ['oculos-1-5'] = {nome = 'Juliete (M/F) 1-5', peso=0.02, model=7, arg='oculos', style='1', text='5'},
        ['oculos-1-6'] = {nome = 'Juliete (M/F) 1-6', peso=0.02, model=7, arg='oculos', style='1', text='6'},
        ['oculos-1-7'] = {nome = 'Juliete (M/F) 1-7', peso=0.02, model=7, arg='oculos', style='1', text='7'},
        ['oculos-1-8'] = {nome = 'Juliete (M/F) 1-8', peso=0.02, model=7, arg='oculos', style='1', text='8'},
        ['oculos-1-9'] = {nome = 'Juliete (M/F) 1-9', peso=0.02, model=7, arg='oculos', style='1', text='9'},
        ['oculos-1-10'] = {nome = 'Juliete (M/F) 1-10', peso=0.02, model=7, arg='oculos', style='1', text='10'},
        ['oculos-1-11'] = {nome = 'Juliete (M/F) 1-11', peso=0.02, model=7, arg='oculos', style='1', text='11'},
        ['oculos-1-12'] = {nome = 'Juliete (M/F) 1-12', peso=0.02, model=7, arg='oculos', style='1', text='12'},
        ['oculos-1-13'] = {nome = 'Juliete (M/F) 1-13', peso=0.02, model=7, arg='oculos', style='1', text='13'},
        ['oculos-1-14'] = {nome = 'Juliete (M/F) 1-14', peso=0.02, model=7, arg='oculos', style='1', text='14'},
        ['oculos-1-15'] = {nome = 'Juliete (M/F) 1-15', peso=0.02, model=7, arg='oculos', style='1', text='15'},

        ['oculos-2-1'] = {nome = 'Oculos (M/F) 2-1', peso=0.02, model=7, arg='oculos', style='2', text='1'},
        ['oculos-2-2'] = {nome = 'Oculos (M/F) 2-2', peso=0.02, model=7, arg='oculos', style='2', text='2'},
        ['oculos-2-3'] = {nome = 'Oculos (M/F) 2-3', peso=0.02, model=7, arg='oculos', style='2', text='3'},
        ['oculos-2-4'] = {nome = 'Oculos (M/F) 2-4', peso=0.02, model=7, arg='oculos', style='2', text='4'},
        ['oculos-2-5'] = {nome = 'Oculos (M/F) 2-5', peso=0.02, model=7, arg='oculos', style='2', text='5'},
        ['oculos-2-6'] = {nome = 'Oculos (M/F) 2-6', peso=0.02, model=7, arg='oculos', style='2', text='6'},
        ['oculos-2-7'] = {nome = 'Oculos (M/F) 2-7', peso=0.02, model=7, arg='oculos', style='2', text='7'},
        ['oculos-2-8'] = {nome = 'Oculos (M/F) 2-8', peso=0.02, model=7, arg='oculos', style='2', text='8'},

        ['sandalia-1-1'] = {nome = 'Sandalia (M/F) 1-1', peso=0.02, model=7, arg='tenis', style='1', text='1'},
        ['sandalia-1-2'] = {nome = 'Sandalia (M/F) 1-2', peso=0.02, model=7, arg='tenis', style='1', text='2'},
        ['sandalia-1-3'] = {nome = 'Sandalia (M/F) 1-3', peso=0.02, model=7, arg='tenis', style='1', text='3'},
        ['sandalia-1-4'] = {nome = 'Sandalia (M/F) 1-4', peso=0.02, model=7, arg='tenis', style='1', text='4'},
        ['sandalia-1-5'] = {nome = 'Sandalia (M/F) 1-5', peso=0.02, model=7, arg='tenis', style='1', text='5'},
        ['sandalia-1-6'] = {nome = 'Sandalia (M/F) 1-5', peso=0.02, model=7, arg='tenis', style='1', text='6'},
        ['sandalia-1-7'] = {nome = 'Sandalia (M/F) 1-6', peso=0.02, model=7, arg='tenis', style='1', text='7'},
        ['sandalia-1-8'] = {nome = 'Sandalia (M/F) 1-7', peso=0.02, model=7, arg='tenis', style='1', text='8'},
        ['sandalia-1-9'] = {nome = 'Sandalia (M/F) 1-8', peso=0.02, model=7, arg='tenis', style='1', text='9'},

        ['sandalia-5-1'] = {nome = 'Sandalia (M/F) 5-1', peso=0.02, model=7, arg='tenis', style='5', text='1'},
        ['sandalia-5-2'] = {nome = 'Sandalia (M/F) 5-2', peso=0.02, model=7, arg='tenis', style='5', text='2'},
        ['sandalia-5-3'] = {nome = 'Sandalia (M/F) 5-3', peso=0.02, model=7, arg='tenis', style='5', text='3'},
        ['sandalia-5-4'] = {nome = 'Sandalia (M/F) 5-3', peso=0.02, model=7, arg='tenis', style='5', text='4'},
        ['sandalia-5-5'] = {nome = 'Sandalia (M/F) 5-3', peso=0.02, model=7, arg='tenis', style='5', text='5'},
        ['sandalia-5-6'] = {nome = 'Sandalia (M/F) 5-3', peso=0.02, model=7, arg='tenis', style='5', text='6'},
        ['sandalia-5-7'] = {nome = 'Sandalia (M/F) 5-3', peso=0.02, model=7, arg='tenis', style='5', text='7'},
        ['sandalia-5-8'] = {nome = 'Sandalia (M/F) 5-3', peso=0.02, model=7, arg='tenis', style='5', text='8'},
        ['sandalia-5-9'] = {nome = 'Sandalia (M/F) 5-3', peso=0.02, model=7, arg='tenis', style='5', text='9'},

        -- << TENIS MASCULINO >>

        ['tenis-2-1'] = {nome = 'Tenis (M) 2-1', peso=0.02, model=7, arg='tenis', style='2', text='1'},
        ['tenis-2-2'] = {nome = 'Tenis (M) 2-2', peso=0.02, model=7, arg='tenis', style='2', text='2'},
        ['tenis-2-3'] = {nome = 'Tenis (M) 2-3', peso=0.02, model=7, arg='tenis', style='2', text='3'},
        ['tenis-2-4'] = {nome = 'Tenis (M) 2-4', peso=0.02, model=7, arg='tenis', style='2', text='4'},
        ['tenis-2-5'] = {nome = 'Tenis (M) 2-5', peso=0.02, model=7, arg='tenis', style='2', text='5'},
        ['tenis-2-6'] = {nome = 'Tenis (M) 2-6', peso=0.02, model=7, arg='tenis', style='2', text='6'},
        ['tenis-2-7'] = {nome = 'Tenis (M) 2-7', peso=0.02, model=7, arg='tenis', style='2', text='7'},
        ['tenis-2-8'] = {nome = 'Tenis (M) 2-8', peso=0.02, model=7, arg='tenis', style='2', text='8'},
        ['tenis-2-9'] = {nome = 'Tenis (M) 2-9', peso=0.02, model=7, arg='tenis', style='2', text='9'},

        ['tenis-3-1'] = {nome = 'Tenis (M) 3-1', peso=0.02, model=7, arg='tenis', style='3', text='1'},
        ['tenis-3-2'] = {nome = 'Tenis (M) 3-2', peso=0.02, model=7, arg='tenis', style='3', text='2'},
        ['tenis-3-3'] = {nome = 'Tenis (M) 3-3', peso=0.02, model=7, arg='tenis', style='3', text='3'},
        ['tenis-3-4'] = {nome = 'Tenis (M) 3-4', peso=0.02, model=7, arg='tenis', style='3', text='4'},
        ['tenis-3-5'] = {nome = 'Tenis (M) 3-5', peso=0.02, model=7, arg='tenis', style='3', text='5'},
        ['tenis-3-6'] = {nome = 'Tenis (M) 3-6', peso=0.02, model=7, arg='tenis', style='3', text='6'},

        ['tenis-4-1'] = {nome = 'Tenis (M) 4-1', peso=0.02, model=7, arg='tenis', style='4', text='1'},
        ['tenis-4-2'] = {nome = 'Tenis (M) 4-2', peso=0.02, model=7, arg='tenis', style='4', text='2'},
        ['tenis-4-3'] = {nome = 'Tenis (M) 4-3', peso=0.02, model=7, arg='tenis', style='4', text='3'},

        ['tenis-6-1'] = {nome = 'Tenis (M) 6-1', peso=0.02, model=7, arg='tenis', style='6', text='1'},
        ['tenis-6-2'] = {nome = 'Tenis (M) 6-2', peso=0.02, model=7, arg='tenis', style='6', text='2'},
        ['tenis-6-3'] = {nome = 'Tenis (M) 6-3', peso=0.02, model=7, arg='tenis', style='6', text='3'},
        ['tenis-6-4'] = {nome = 'Tenis (M) 6-4', peso=0.02, model=7, arg='tenis', style='6', text='4'},
        ['tenis-6-5'] = {nome = 'Tenis (M) 6-5', peso=0.02, model=7, arg='tenis', style='6', text='5'},
        ['tenis-6-6'] = {nome = 'Tenis (M) 6-6', peso=0.02, model=7, arg='tenis', style='6', text='6'},

        ['tenis-7-1'] = {nome = 'Tenis (M) 7-1', peso=0.02, model=7, arg='tenis', style='7', text='1'},
        ['tenis-7-2'] = {nome = 'Tenis (M) 7-2', peso=0.02, model=7, arg='tenis', style='7', text='2'},
        ['tenis-7-3'] = {nome = 'Tenis (M) 7-3', peso=0.02, model=7, arg='tenis', style='7', text='3'},
        ['tenis-7-4'] = {nome = 'Tenis (M) 7-4', peso=0.02, model=7, arg='tenis', style='7', text='4'},
        ['tenis-7-5'] = {nome = 'Tenis (M) 7-5', peso=0.02, model=7, arg='tenis', style='7', text='5'},

        ['tenis-8-1'] = {nome = 'Tenis (M) 8-1', peso=0.02, model=7, arg='tenis', style='8', text='1'},
        ['tenis-8-2'] = {nome = 'Tenis (M) 8-2', peso=0.02, model=7, arg='tenis', style='8', text='2'},
        ['tenis-8-3'] = {nome = 'Tenis (M) 8-3', peso=0.02, model=7, arg='tenis', style='8', text='3'},
        ['tenis-8-4'] = {nome = 'Tenis (M) 8-4', peso=0.02, model=7, arg='tenis', style='8', text='4'},

        -- << CAMISAS FEMININAS >>
        ['blusaf-1-1'] = {nome = 'Blusa (F) 1-1', peso=0.02, model=9, arg='blusa', style='1', text='1'},
        ['blusaf-1-2'] = {nome = 'Blusa (F) 1-2', peso=0.02, model=9, arg='blusa', style='1', text='2'},
        ['blusaf-1-3'] = {nome = 'Blusa (F) 1-3', peso=0.02, model=9, arg='blusa', style='1', text='3'},
        ['blusaf-1-4'] = {nome = 'Blusa (F) 1-4', peso=0.02, model=9, arg='blusa', style='1', text='4'},
        ['blusaf-1-5'] = {nome = 'Blusa (F) 1-5', peso=0.02, model=9, arg='blusa', style='1', text='5'},
        ['blusaf-1-6'] = {nome = 'Blusa (F) 1-6', peso=0.02, model=9, arg='blusa', style='1', text='6'},
        ['blusaf-1-7'] = {nome = 'Blusa (F) 1-7', peso=0.02, model=9, arg='blusa', style='1', text='7'},

        ['blusaf-3-1'] = {nome = 'Blusa (F) 3-1', peso=0.02, model=9, arg='blusa', style='3', text='1'},
        ['blusaf-3-2'] = {nome = 'Blusa (F) 3-2', peso=0.02, model=9, arg='blusa', style='3', text='2'},
        ['blusaf-3-3'] = {nome = 'Blusa (F) 3-3', peso=0.02, model=9, arg='blusa', style='3', text='3'},
        ['blusaf-3-4'] = {nome = 'Blusa (F) 3-4', peso=0.02, model=9, arg='blusa', style='3', text='4'},
        ['blusaf-3-5'] = {nome = 'Blusa (F) 3-5', peso=0.02, model=9, arg='blusa', style='3', text='5'},
        ['blusaf-3-6'] = {nome = 'Blusa (F) 3-6', peso=0.02, model=9, arg='blusa', style='3', text='6'},
        ['blusaf-3-7'] = {nome = 'Blusa (F) 3-7', peso=0.02, model=9, arg='blusa', style='3', text='7'},
        ['blusaf-3-8'] = {nome = 'Blusa (F) 3-8', peso=0.02, model=9, arg='blusa', style='3', text='8'},
        ['blusaf-3-9'] = {nome = 'Blusa (F) 3-9', peso=0.02, model=9, arg='blusa', style='3', text='9'},
        ['blusaf-3-10'] = {nome = 'Blusa (F) 3-10', peso=0.02, model=9, arg='blusa', style='3', text='10'},
        ['blusaf-3-11'] = {nome = 'Blusa (F) 3-11', peso=0.02, model=9, arg='blusa', style='3', text='11'},
        ['blusaf-3-12'] = {nome = 'Blusa (F) 3-12', peso=0.02, model=9, arg='blusa', style='3', text='12'},
        ['blusaf-3-13'] = {nome = 'Blusa (F) 3-13', peso=0.02, model=9, arg='blusa', style='3', text='13'},

        ['blusaf-4-1'] = {nome = 'Blusa (F) 4-1', peso=0.02, model=9, arg='blusa', style='4', text='1'},
        ['blusaf-4-2'] = {nome = 'Blusa (F) 4-2', peso=0.02, model=9, arg='blusa', style='4', text='2'},
        ['blusaf-4-3'] = {nome = 'Blusa (F) 4-3', peso=0.02, model=9, arg='blusa', style='4', text='3'},
        ['blusaf-4-4'] = {nome = 'Blusa (F) 4-4', peso=0.02, model=9, arg='blusa', style='4', text='4'},
        ['blusaf-4-5'] = {nome = 'Blusa (F) 4-5', peso=0.02, model=9, arg='blusa', style='4', text='5'},
        ['blusaf-4-6'] = {nome = 'Blusa (F) 4-6', peso=0.02, model=9, arg='blusa', style='4', text='6'},
        ['blusaf-4-7'] = {nome = 'Blusa (F) 4-7', peso=0.02, model=9, arg='blusa', style='4', text='7'},
        ['blusaf-4-8'] = {nome = 'Blusa (F) 4-8', peso=0.02, model=9, arg='blusa', style='4', text='8'},
        ['blusaf-4-9'] = {nome = 'Blusa (F) 4-9', peso=0.02, model=9, arg='blusa', style='4', text='9'},
        ['blusaf-4-10'] = {nome = 'Blusa (F) 4-10', peso=0.02, model=9, arg='blusa', style='4', text='10'},
        ['blusaf-4-11'] = {nome = 'Blusa (F) 4-11', peso=0.02, model=9, arg='blusa', style='4', text='11'},
        ['blusaf-4-12'] = {nome = 'Blusa (F) 4-12', peso=0.02, model=9, arg='blusa', style='4', text='12'},

        ['blusaf-5-1'] = {nome = 'Blusa (F) 5-1', peso=0.02, model=9, arg='blusa', style='5', text='1'},
        ['blusaf-5-2'] = {nome = 'Blusa (F) 5-2', peso=0.02, model=9, arg='blusa', style='5', text='2'},
        ['blusaf-5-3'] = {nome = 'Blusa (F) 5-3', peso=0.02, model=9, arg='blusa', style='5', text='3'},
        ['blusaf-5-4'] = {nome = 'Blusa (F) 5-4', peso=0.02, model=9, arg='blusa', style='5', text='4'},
        ['blusaf-5-5'] = {nome = 'Blusa (F) 5-5', peso=0.02, model=9, arg='blusa', style='5', text='5'},
        ['blusaf-5-6'] = {nome = 'Blusa (F) 5-6', peso=0.02, model=9, arg='blusa', style='5', text='6'},
        ['blusaf-5-7'] = {nome = 'Blusa (F) 5-7', peso=0.02, model=9, arg='blusa', style='5', text='7'},
        ['blusaf-5-8'] = {nome = 'Blusa (F) 5-8', peso=0.02, model=9, arg='blusa', style='5', text='8'},
        ['blusaf-5-9'] = {nome = 'Blusa (F) 5-9', peso=0.02, model=9, arg='blusa', style='5', text='9'},

        ['blusaf-6-1'] = {nome = 'Blusa (F) 6-1', peso=0.02, model=9, arg='blusa', style='6', text='1'},
        ['blusaf-6-2'] = {nome = 'Blusa (F) 6-2', peso=0.02, model=9, arg='blusa', style='6', text='2'},
        ['blusaf-6-3'] = {nome = 'Blusa (F) 6-3', peso=0.02, model=9, arg='blusa', style='6', text='3'},
        ['blusaf-6-4'] = {nome = 'Blusa (F) 6-4', peso=0.02, model=9, arg='blusa', style='6', text='4'},
        ['blusaf-6-5'] = {nome = 'Blusa (F) 6-5', peso=0.02, model=9, arg='blusa', style='6', text='5'},
        ['blusaf-6-6'] = {nome = 'Blusa (F) 6-6', peso=0.02, model=9, arg='blusa', style='6', text='6'},
        ['blusaf-6-7'] = {nome = 'Blusa (F) 6-7', peso=0.02, model=9, arg='blusa', style='6', text='7'},
        ['blusaf-6-8'] = {nome = 'Blusa (F) 6-8', peso=0.02, model=9, arg='blusa', style='6', text='8'},

        ['vestidof-2-1'] = {nome = 'Vestido (F) 2-1', peso=0.02, model=9, arg='blusa', style='2', text='1'},
        ['vestidof-2-2'] = {nome = 'Vestido (F) 2-2', peso=0.02, model=9, arg='blusa', style='2', text='2'},
        ['vestidof-2-3'] = {nome = 'Vestido (F) 2-3', peso=0.02, model=9, arg='blusa', style='2', text='3'},
        ['vestidof-2-4'] = {nome = 'Vestido (F) 2-4', peso=0.02, model=9, arg='blusa', style='2', text='4'},
        ['vestidof-2-5'] = {nome = 'Vestido (F) 2-5', peso=0.02, model=9, arg='blusa', style='2', text='5'},
        ['vestidof-2-6'] = {nome = 'Vestido (F) 2-6', peso=0.02, model=9, arg='blusa', style='2', text='6'},
        ['vestidof-2-7'] = {nome = 'Vestido (F) 2-7', peso=0.02, model=9, arg='blusa', style='2', text='7'},
        ['vestidof-2-8'] = {nome = 'Vestido (F) 2-8', peso=0.02, model=9, arg='blusa', style='2', text='8'},
        ['vestidof-2-9'] = {nome = 'Vestido (F) 2-9', peso=0.02, model=9, arg='blusa', style='2', text='9'},
        ['vestidof-2-10'] = {nome = 'Vestido (F) 2-10', peso=0.02, model=9, arg='blusa', style='2', text='10'},

        ['calcaf-1-1'] = {nome = 'Calca (F) 1-1', peso=0.02, model=9, arg='calca', style='1', text='1'},
        ['calcaf-1-2'] = {nome = 'Calca (F) 1-2', peso=0.02, model=9, arg='calca', style='1', text='2'},
        ['calcaf-1-3'] = {nome = 'Calca (F) 1-3', peso=0.02, model=9, arg='calca', style='1', text='3'},
        ['calcaf-1-4'] = {nome = 'Calca (F) 1-4', peso=0.02, model=9, arg='calca', style='1', text='4'},
        ['calcaf-1-5'] = {nome = 'Calca (F) 1-5', peso=0.02, model=9, arg='calca', style='1', text='5'},

        ['calcaf-3-1'] = {nome = 'Calca (F) 3-1', peso=0.02, model=9, arg='calca', style='3', text='1'},
        ['calcaf-3-2'] = {nome = 'Calca (F) 3-2', peso=0.02, model=9, arg='calca', style='3', text='2'},
        ['calcaf-3-3'] = {nome = 'Calca (F) 3-3', peso=0.02, model=9, arg='calca', style='3', text='3'},
        ['calcaf-3-4'] = {nome = 'Calca (F) 3-4', peso=0.02, model=9, arg='calca', style='3', text='4'},
        ['calcaf-3-5'] = {nome = 'Calca (F) 3-5', peso=0.02, model=9, arg='calca', style='3', text='5'},
        ['calcaf-3-6'] = {nome = 'Calca (F) 3-6', peso=0.02, model=9, arg='calca', style='3', text='6'},
        ['calcaf-3-7'] = {nome = 'Calca (F) 3-7', peso=0.02, model=9, arg='calca', style='3', text='7'},
        ['calcaf-3-8'] = {nome = 'Calca (F) 3-8', peso=0.02, model=9, arg='calca', style='3', text='8'},
        ['calcaf-3-9'] = {nome = 'Calca (F) 3-9', peso=0.02, model=9, arg='calca', style='3', text='9'},
        ['calcaf-3-10'] = {nome = 'Calca (F) 3-10', peso=0.02, model=9, arg='calca', style='3', text='10'},

        ['calcaf-4-1'] = {nome = 'Calca (F) 4-1', peso=0.02, model=9, arg='calca', style='4', text='1'},
        ['calcaf-4-2'] = {nome = 'Calca (F) 4-2', peso=0.02, model=9, arg='calca', style='4', text='2'},
        ['calcaf-4-3'] = {nome = 'Calca (F) 4-3', peso=0.02, model=9, arg='calca', style='4', text='3'},
        ['calcaf-4-4'] = {nome = 'Calca (F) 4-4', peso=0.02, model=9, arg='calca', style='4', text='4'},
        ['calcaf-4-5'] = {nome = 'Calca (F) 4-5', peso=0.02, model=9, arg='calca', style='4', text='5'},
        ['calcaf-4-6'] = {nome = 'Calca (F) 4-6', peso=0.02, model=9, arg='calca', style='4', text='6'},
        ['calcaf-4-7'] = {nome = 'Calca (F) 4-7', peso=0.02, model=9, arg='calca', style='4', text='7'},
        ['calcaf-4-8'] = {nome = 'Calca (F) 4-8', peso=0.02, model=9, arg='calca', style='4', text='8'},
        ['calcaf-4-9'] = {nome = 'Calca (F) 4-9', peso=0.02, model=9, arg='calca', style='4', text='9'},
        ['calcaf-4-10'] = {nome = 'Calca (F) 4-10', peso=0.02, model=9, arg='calca', style='4', text='10'},
        ['calcaf-4-11'] = {nome = 'Calca (F) 4-11', peso=0.02, model=9, arg='calca', style='4', text='11'},
        ['calcaf-4-12'] = {nome = 'Calca (F) 4-12', peso=0.02, model=9, arg='calca', style='4', text='12'},

        ['shortf-2-1'] = {nome = 'Short (F) 2-1', peso=0.02, model=9, arg='calca', style='2', text='1'},
        ['shortf-2-2'] = {nome = 'Short (F) 2-2', peso=0.02, model=9, arg='calca', style='2', text='2'},
        ['shortf-2-3'] = {nome = 'Short (F) 2-3', peso=0.02, model=9, arg='calca', style='2', text='3'},
        ['shortf-2-4'] = {nome = 'Short (F) 2-4', peso=0.02, model=9, arg='calca', style='2', text='4'},
        ['shortf-2-5'] = {nome = 'Short (F) 2-5', peso=0.02, model=9, arg='calca', style='2', text='5'},
        ['shortf-2-6'] = {nome = 'Short (F) 2-6', peso=0.02, model=9, arg='calca', style='2', text='6'},
        ['shortf-2-7'] = {nome = 'Short (F) 2-7', peso=0.02, model=9, arg='calca', style='2', text='7'},
        ['shortf-2-8'] = {nome = 'Short (F) 2-8', peso=0.02, model=9, arg='calca', style='2', text='8'},
        ['shortf-2-9'] = {nome = 'Short (F) 2-9', peso=0.02, model=9, arg='calca', style='2', text='9'},
        ['shortf-2-10'] = {nome = 'Short (F) 2-10', peso=0.02, model=9, arg='calca', style='2', text='10'},
        ['shortf-2-11'] = {nome = 'Short (F) 2-11', peso=0.02, model=9, arg='calca', style='2', text='11'},
        ['shortf-2-12'] = {nome = 'Short (F) 2-12', peso=0.02, model=9, arg='calca', style='2', text='12'},
        ['shortf-2-13'] = {nome = 'Short (F) 2-13', peso=0.02, model=9, arg='calca', style='2', text='13'},
        ['shortf-2-14'] = {nome = 'Short (F) 2-14', peso=0.02, model=9, arg='calca', style='2', text='14'},
        ['shortf-2-15'] = {nome = 'Short (F) 2-15', peso=0.02, model=9, arg='calca', style='2', text='15'},
        ['shortf-2-16'] = {nome = 'Short (F) 2-16', peso=0.02, model=9, arg='calca', style='2', text='16'},
        ['shortf-2-17'] = {nome = 'Short (F) 2-17', peso=0.02, model=9, arg='calca', style='2', text='17'},

        ['tenisf-4-1'] = {nome = 'Tenis (F) 4-1', peso=0.02, model=9, arg='tenis', style='4', text='1'},
        ['tenisf-4-2'] = {nome = 'Tenis (F) 4-2', peso=0.02, model=9, arg='tenis', style='4', text='2'},
        ['tenisf-4-3'] = {nome = 'Tenis (F) 4-3', peso=0.02, model=9, arg='tenis', style='4', text='3'},
        ['tenisf-4-4'] = {nome = 'Tenis (F) 4-4', peso=0.02, model=9, arg='tenis', style='4', text='4'},
        ['tenisf-4-5'] = {nome = 'Tenis (F) 4-5', peso=0.02, model=9, arg='tenis', style='4', text='5'},
        ['tenisf-4-6'] = {nome = 'Tenis (F) 4-6', peso=0.02, model=9, arg='tenis', style='4', text='6'},
        ['tenisf-4-7'] = {nome = 'Tenis (F) 4-7', peso=0.02, model=9, arg='tenis', style='4', text='7'},
        ['tenisf-4-8'] = {nome = 'Tenis (F) 4-8', peso=0.02, model=9, arg='tenis', style='4', text='8'},
        ['tenisf-4-9'] = {nome = 'Tenis (F) 4-9', peso=0.02, model=9, arg='tenis', style='4', text='9'},
        ['tenisf-4-10'] = {nome = 'Tenis (F) 4-10', peso=0.02, model=9, arg='tenis', style='4', text='10'},

        ['saltof-3-1'] = {nome = 'Salto (F) 3-1', peso=0.02, model=9, arg='tenis', style='3', text='1'},
        ['saltof-3-2'] = {nome = 'Salto (F) 3-2', peso=0.02, model=9, arg='tenis', style='3', text='2'},
        ['saltof-3-3'] = {nome = 'Salto (F) 3-3', peso=0.02, model=9, arg='tenis', style='3', text='3'},
        ['saltof-3-4'] = {nome = 'Salto (F) 3-4', peso=0.02, model=9, arg='tenis', style='3', text='4'},
        ['saltof-3-5'] = {nome = 'Salto (F) 3-5', peso=0.02, model=9, arg='tenis', style='3', text='5'},
        ['saltof-3-6'] = {nome = 'Salto (F) 3-6', peso=0.02, model=9, arg='tenis', style='3', text='6'},
        ['saltof-3-7'] = {nome = 'Salto (F) 3-7', peso=0.02, model=9, arg='tenis', style='3', text='7'},
        ['saltof-3-8'] = {nome = 'Salto (F) 3-8', peso=0.02, model=9, arg='tenis', style='3', text='8'},
        ['saltof-3-9'] = {nome = 'Salto (F) 3-9', peso=0.02, model=9, arg='tenis', style='3', text='9'},
        ['saltof-3-10'] = {nome = 'Salto (F) 3-10', peso=0.02, model=9, arg='tenis', style='3', text='10'},

        ['rasteiraf-6-1'] = {nome = 'Rasteira (F) 6-1', peso=0.02, model=9, arg='tenis', style='6', text='1'},
        ['rasteiraf-6-2'] = {nome = 'Rasteira (F) 6-2', peso=0.02, model=9, arg='tenis', style='6', text='2'},
        ['rasteiraf-6-3'] = {nome = 'Rasteira (F) 6-3', peso=0.02, model=9, arg='tenis', style='6', text='3'},
        ['rasteiraf-6-4'] = {nome = 'Rasteira (F) 6-4', peso=0.02, model=9, arg='tenis', style='6', text='4'},
        ['rasteiraf-6-5'] = {nome = 'Rasteira (F) 6-5', peso=0.02, model=9, arg='tenis', style='6', text='5'},
        ['rasteiraf-6-6'] = {nome = 'Rasteira (F) 6-6', peso=0.02, model=9, arg='tenis', style='6', text='6'},
        ['rasteiraf-6-7'] = {nome = 'Rasteira (F) 6-7', peso=0.02, model=9, arg='tenis', style='6', text='7'},
        ['rasteiraf-6-8'] = {nome = 'Rasteira (F) 6-8', peso=0.02, model=9, arg='tenis', style='6', text='8'},
        ['rasteiraf-6-9'] = {nome = 'Rasteira (F) 6-9', peso=0.02, model=9, arg='tenis', style='6', text='9'},
        ['rasteiraf-6-10'] = {nome = 'Rasteira (F) 6-10', peso=0.02, model=9, arg='tenis', style='6', text='10'},

        ['sapatilhaf-5-1'] = {nome = 'Sapatilha (F) 1-1', peso=0.02, model=9, arg='tenis', style='5', text='1'},
        ['sapatilhaf-5-2'] = {nome = 'Sapatilha (F) 1-2', peso=0.02, model=9, arg='tenis', style='5', text='2'},
        ['sapatilhaf-5-3'] = {nome = 'Sapatilha (F) 1-3', peso=0.02, model=9, arg='tenis', style='5', text='3'},
        ['sapatilhaf-5-4'] = {nome = 'Sapatilha (F) 1-4', peso=0.02, model=9, arg='tenis', style='5', text='4'},
        ['sapatilhaf-5-5'] = {nome = 'Sapatilha (F) 1-5', peso=0.02, model=9, arg='tenis', style='5', text='5'},
        ['sapatilhaf-5-6'] = {nome = 'Sapatilha (F) 1-6', peso=0.02, model=9, arg='tenis', style='5', text='6'},
        ['sapatilhaf-5-7'] = {nome = 'Sapatilha (F) 1-7', peso=0.02, model=9, arg='tenis', style='5', text='7'},
        ['sapatilhaf-5-8'] = {nome = 'Sapatilha (F) 1-8', peso=0.02, model=9, arg='tenis', style='5', text='8'},
        ['sapatilhaf-5-9'] = {nome = 'Sapatilha (F) 1-9', peso=0.02, model=9, arg='tenis', style='5', text='9'},

        ['sutiaf-1-1'] = {nome = 'Sutia (F) 1-1', peso=0.02, model=9, arg='sutia', style='1', text='1'},
        ['sutiaf-1-2'] = {nome = 'Sutia (F) 1-2', peso=0.02, model=9, arg='sutia', style='1', text='2'},
        ['sutiaf-1-3'] = {nome = 'Sutia (F) 1-3', peso=0.02, model=9, arg='sutia', style='1', text='3'},

        ['calcinhaf-1-1'] = {nome = 'Calcinha (F) 1-1', peso=0.02, model=9, arg='calcinha', style='1', text='1'},
        ['calcinhaf-1-2'] = {nome = 'Calcinha (F) 1-2', peso=0.02, model=9, arg='calcinha', style='1', text='2'},
        ['calcinhaf-1-3'] = {nome = 'Calcinha (F) 1-3', peso=0.02, model=9, arg='calcinha', style='1', text='3'},

    },

    baus = {
        -- BANCADA BURGUERSHOT
        {
            position = {803.038, -1611.809, 13.78 -0.5, 90},
            object = 2332,
            pesoMax = 10,
			invisible = true,
            nome = 'Bancada',
            slots = 5,
            acl = 'Everyone',
        },

        { -- Cluckin
            position = {2389.503, -1909.7, 14.38 -1.2, 90},
            object = 2332,
            pesoMax = 10,
			invisible = true,
            nome = 'Bancada',
            slots = 5,
            acl = 'Everyone',
        },

        { -- Cluckin GELADEIRA
        position = {2399.005, -1913.552, 13.547, 90},
        object = 2332,
        pesoMax = 200,
        invisible = true,
        nome = 'Geladeira Cluckin Bell',
        acl = 'CluckinBell',
    },
    },

    shops = {
		{
			name = 'Xoomer',
			blip = 47,
			type = 'buy',
			model = 0,
			position = {1345.3387451172,-1761.4656982422,13.546875, 270},
			acl = 'Everyone',
			items = {
				{item = 'caixacigarro', preco=200},
				{item = 'isqueiro', preco=90},
				{item = 'seda', preco=10},
				{item = 'gasolina', preco=80},
				{item = 'hamburguerc', preco=400},
				{item = 'agua', preco=300},
				{item = 'mochila', preco=1000},
			},
		},
		{
			name = 'Xoomer',
			blip = 47,
			type = 'buy',
			model = 0,
			position = {614.37701416016,-1509.7409667969,15.14687538147, 180},
			acl = 'Everyone',
			items = {
				{item = 'caixacigarro', preco=200},
				{item = 'isqueiro', preco=90},
				{item = 'seda', preco=10},
                {item = 'gasolina', preco=80},
                {item = 'hamburguerc', preco=400},
				{item = 'agua', preco=300},
                {item = 'mochila', preco=1000},
			},
		},


		{
			name = 'Xoomer',
			blip = 47,
			type = 'buy',
			model = 0,
			position = {2426.0981445312,-1786.2587890625,13.64687538147, 0},
			acl = 'Everyone',
			items = {
				{item = 'caixacigarro', preco=200},
				{item = 'isqueiro', preco=90},
				{item = 'seda', preco=10},
                {item = 'gasolina', preco=80},
                {item = 'hamburguerc', preco=400},
				{item = 'agua', preco=300},
                {item = 'mochila', preco=1000},
			},
		},

		{
			name = 'Xoomer',
			blip = 47,
			type = 'buy',
			model = 0,
			position = {658.24102783203,-611.67828369141,16.44687461853, 270},
			acl = 'Everyone',
			items = {
				{item = 'caixacigarro', preco=200},
				{item = 'isqueiro', preco=90},
				{item = 'seda', preco=10},
                {item = 'gasolina', preco=80},
                {item = 'hamburguerc', preco=400},
				{item = 'agua', preco=300},
                {item = 'mochila', preco=1000},
			},
		},

		{
			name = 'Xoomer',
			blip = 47,
			type = 'buy',
			model = 0,
			position = {-2420.0107421875,969.80517578125,45.296875, 270},
			acl = 'Everyone',
			items = {
				{item = 'caixacigarro', preco=200},
				{item = 'isqueiro', preco=90},
				{item = 'seda', preco=10},
                {item = 'gasolina', preco=80},
                {item = 'hamburguerc', preco=400},
				{item = 'agua', preco=300},
                {item = 'mochila', preco=1000},
			},
		},

		-- << BURGUERSHOT >>


		{
			name = 'Cluckin Bell',
			blip = 48,
			type = 'buy',
			model = 167,
			position = {2389.454, -1912.637, 13.547 -10, 266},
			acl = 'CluckinBell',
			items = {
				{item = 'cbrefri', preco = 100},
				{item = 'cbcebola', preco = 150},
				{item = 'cbfritas', preco = 150},
				{item = 'cbcombo', preco = 500},
			},
		},

		{
			name = 'The Well Stacked Pizza',
			blip = 45,
			type = 'buy',
			model = 155,
			position = {2118.035, -1812.547, 13.555, 182},
			acl = 'Pizzaria',
			items = {
				{item = 'twrefri', preco = 150},
				{item = 'pizza', preco = 150},
				{item = 'twfritas', preco = 150},
				{item = 'twcombo', preco = 500},
			},
		},

		-- << MECANICA >>
		{
			name = 'Ferramentas',
			type = 'buy',
			model = 50,
			position = {952.86572265625,-1556.4395751953,13.576910018921, 90},
			acl = 'Mecanico',
			items = {
				{item = 'kitreparo', preco=300},
				{item = 'motora', preco=400},
				{item = 'motorb', preco=700},
				{item = 'pneua', preco=100},
				{item = 'pneub', preco=200},
				{item = 'portaa', preco=250},
				{item = 'turbina', preco=15000},
			},
		},

		-- << MERCADO NEGRO >>
		--[[
		{
			type = 'buy',
			model = 113,
			position = {-636.681, 1446.539, 13.996, 216},
			acl = 'Everyone',
			items = {
				{item = 'lockpick', preco=5000},
				{item = 'algema', preco=3000},
			},
		},]]
        -- << JOALHERIA >>

		        -- << PENHORES >>
				{
					type = 'sell',
					model = 95,
					position = {994.23, -1295.578, 13.547, 178},
					blip = 58,
					acl = 'Everyone',
					items = {
						{item = 'alianca', preco=200},
						{item = 'anel', preco=175},
						{item = 'bracelete', preco=215},
						{item = 'colar', preco=230},
						{item = 'mouse', preco=100},
						{item = 'pilhas', preco=80},
						{item = 'teclado', preco=120},
						{item = 'xbox', preco=300},
					},
				},

						        -- << PENHORES >>
				{
					type = 'sell',
					model = 223,
					position = {996.119, -1295.577, 13.547, 177},
					blip = 64,
					acl = 'Everyone',
					items = {
						{item = 'faca', preco=500},
						{item = 'radio', preco=450},
						{item = 'celular', preco=600},
						{item = 'makita', preco=850},
						{item = 'pendrive', preco=300},
						{item = 'acessorios-1-1', preco=1000},
						{item = 'acessorios-1-2', preco=700},
						{item = 'acessorios-2-1', preco=400},
						{item = 'acessorios-2-2', preco=200},

					},
				},

        -- << pescaria >>

        {
            type = 'sell',
            model = 35,
            position = {-1353.9018554688,2057.6909179688,53.1171875, 270},
			blip = 34,
            acl = 'Everyone',
            items = {
                {item = 'cavala', preco=30},
                {item = 'bagre', preco=170},
                {item = 'bacalhau', preco=90},
                {item = 'pacu', preco=70},
                {item = 'carpa', preco=55},
                {item = 'camarao', preco=45},
                {item = 'tilapia', preco=210},
                {item = 'tambaqui', preco=110},
            },
        },

        -- << ammunation >>
        {
            type = 'buy',
            model = 35,
            position = {1368.5679931641,-1279.8109130859,13.546875, 90},
            acl = 'Everyone',
            blip = 18,
            items = {
                {item = 'vara', preco=250},
                {item = 'picareta', preco = 1000},
                {item = 'faca', preco = 1500},
                {item = 'martelo', preco = 1000},
                {item = 'soqueira', preco = 750},
            },
        },

        {
            type = 'buy',
            model = 286,
            position = {1562.25, -1689.007, 16.203, 270},
            acl = 'Policial',
            items = {
                {item = 'taurus', preco=1000},
                {item = 'mp5', preco = 4000},
                {item = 'imbel', preco = 7000},
                {item = 'mpistola', preco = 10},
                {item = 'msmg', preco = 20},
                {item = 'mfuzil', preco = 30},
                {item = 'algema', preco = 150},
				{item = 'taser', preco = 350},
				{item = 'vest', preco = 500},
				{item = 'cassetete', preco = 400},
                --{item = 'katana', preco = 7000},
                --{item = 'machadog', preco = 9000},
            },
        },


		    -- << Central de Pesca >>
        {
			name = 'Central de Pescaria',
            type = 'buy',
            model = 35,
            position = {2212.1088867188,-2.411678314209,26.926296234131, 188},
            acl = 'Everyone',
            blip = 33,
            items = {
                {item = 'vara', preco=250},
                {item = 'isca', preco = 10},
                {item = 'licensapescador', preco = 2000},
                --{item = 'katana', preco = 7000},
                --{item = 'machadog', preco = 9000},
            },
        },

		{
			name = 'Acessorios',
            type = 'buy',
            model = 25,
            position = {461.50637817383,-1500.7283935547,31.060771942139, 90},
            acl = 'Everyone',
            blip = 51,
            items = {
                {item = 'mascara-11-1', preco=1100},
                {item = 'mascara-11-2', preco = 3000},
                {item = 'mascara-5-1', preco = 1000},
                {item = 'mascara-5-2', preco = 1000},
            },
        },

		--[[ {
			name = 'Hospital',
            type = 'buy',
            model = 70,
            position = {1226.7862548828,-1765.8791503906,13.609375, 50},
            acl = 'Everyone',
            items = {
                {item = 'adrenalina', preco=7000},
            },
        }, ]]

		{
			name = 'Hospital',
            type = 'buy',
            model = 70,
            position = {1242.8011474609,-1737.8905029297,13.609375, 180},
            acl = 'Paramedic',
            items = {
                {item = 'adrenalina', preco=100},
                {item = 'desfibrilador', preco=1500},
                {item = 'gaze', preco=100},
            },
        },

		--{
		-- 	name = 'Imobiliaria',
            --  type = 'buy',
          --  model = 57,
			-- blip = 35,
          --  position = {1684.6416015625,-1343.5003662109,17.436183929443, 270},
         --   acl = 'Everyone',
          --  items = {
             --   {item = 'contratoa', preco=120000},
             --   {item = 'contratob', preco=170000},
             ---   {item = 'contratoc', preco=310000},
             --   {item = 'contratod', preco=370000},
             --   {item = 'contratoe', preco=500000},
             --   {item = 'contratof', preco=650000},
             --   {item = 'contratog', preco=720000},
             --   {item = 'contratoh', preco=900000},
           -- },
       -- },

		{
			name = 'Digital Den',
            type = 'buy',
            model = 57,
			blip = 26,
            position = {1285.7464599609,-1594.4412841797,13.546875, 0},
            acl = 'Everyone',
            items = {
                {item = 'celular', preco=1400},
                {item = 'tablet', preco=900},
                {item = 'laptop', preco=1200},
                {item = 'vpn', preco=2000},
                {item = 'radio', preco=1500},
            },
        },

		{
			name = 'Reciclagem',
            type = 'sell',
            model = 79,
			blip = 59,
            position = {2206.137, -2015.374, 13.898, 24},
            acl = 'Everyone',
            items = {
                {item = 'metal', preco=75},
                {item = 'aluminio', preco=50},
                {item = 'titanium', preco=80},
                {item = 'elastico', preco=10},
                {item = 'ziplock', preco=10},
                {item = 'garrafavazia', preco=5},
                {item = 'fita', preco=7},
                {item = 'garrafaq', preco=70},
				{item = 'pano', preco=15},
                {item = 'tecido', preco=30},
            },
        },

		{
			name = 'Reciclagem',
            type = 'sell',
            model = 78,
			blip = 70,
            position = {2205.312, -2015.721, 13.898, 25},
            acl = 'Everyone',
            items = {
                {item = 'capsula', preco=20},
                {item = 'kevlar', preco=35},
                {item = 'corrente', preco=120},
                {item = 'colar', preco=50},
            },
        },

        {
			name = 'Distribuidora',
            type = 'buy',
            model = 62,
			blip = 21,
            position = {1315.418, -897.682, 39.578, 183},
            acl = 'Everyone',
            items = {
                {item = 'pao', preco=10},
                {item = 'alface', preco=5},
                {item = 'pacotenuggets', preco=30},
                {item = 'pacotecebolas', preco=15},
                {item = 'frango', preco=40},
                {item = 'frangoempanado', preco=40},
                {item = 'uva', preco=10},
                {item = 'banana', preco=10},
                {item = 'garrafavazia', preco=5},
            },
        },
		
	},

    alimentos = {
        ['agua'] = 25,
        ['hamburguerc'] = 25,
        ['sucouva'] = 70,
        ['sucobanana'] = 70,
        ['cbnuggets'] = 35,
        ['cbburguer'] = 80,
        ['cbcebola'] = 35,
        ['frangofrito'] = 80,
    },

    portamalas = {
        [541] = 30,
        [547] = 20,
        [566] = 30,
        [466] = 15,
        [404] = 30,
    },

    health = {
        ['comida'] = 1,
        ['bebida'] = 0.7,
        ['weapon'] = 0.1,
        ['phone'] = 0.2,
    },

    recoil = {
        [33] = { --RIFLE
            x = 0.35, -- pro lado
            y = 1.5, -- pra cima
        },
        [31] = { --M4
            x = 0.35, -- pro lado
            y = 0.20, -- pra cima
        },
        [30] = { --AK
            x = 0.35, -- pro lado
            y = 0.20, -- pra cima
        },
        [24] = { --deagle
            x = 0.30, -- pro lado
            y = 1.5, -- pra cima
        },
        [22] = { --colt
        x = 0.20, -- pro lado
        y = 1.0, -- pra cima
        },
        [25] = { --12
        x = 1.8, -- pro lado
        y = 10.0, -- pra cima
        },
    },
}


function getConfig()
    return cfg
end

function math.round(num, decimals)
    decimals = math.pow(10, decimals or 0)
    num = num * decimals
    if num >= 0 then num = math.floor(num + 0.5) else num = math.ceil(num - 0.5) end
    return num / decimals
end

function formatNumber(number, sep)
	assert(type(tonumber(number))=="number", "Bad argument @'formatNumber' [Expected number at argument 1 got "..type(number).."]")
	assert(not sep or type(sep)=="string", "Bad argument @'formatNumber' [Expected string at argument 2 got "..type(sep).."]")
	local money = number
	for i = 1, tostring(money):len()/3 do
		money = string.gsub(money, "^(-?%d+)(%d%d%d)", "%1"..sep.."%2")
	end
	return money
end

function msg ( player, msg, type, ... )
    return exports.crp_notify:addBox(player, msg, type, ...)
end

--[[ 
cfg.mascaras =
{
 [7] = {
    {"Máscara (M-1 '1')", 14582, 1, 0.0159, -0.141, -0.550, -15, 0, 7, "mascara-1-1"},
    {"Máscara (M-2 '1')", 2783, 1, 0.015, -0.139, -0.550, -15, 0, 7, "mascara-2-1"},
    {"Máscara (M-3 '1')", 3440, 1, 0.009, -0.090, -0.565, -10, 0, 6, "mascara-3-1"},
    {"Máscara (M-4 '1')", 3430, 1, 0.009, -0.090, -0.565, -10, 0, 6, "mascara-4-1"},
    {"Máscara (M-5 '1')", 2785, 1, 0.0045, -0.074, -0.570, -9, 0, 6, "mascara-5-1"},
    {"Máscara (M-5 '2')", 14566, 1, 0.0045, -0.074, -0.570, -9, 0, 6, "mascara-5-2"},
    {"Máscara (M-6 '1')", 14568, 1, 0.0045, -0.085, -0.570, -9, 0, 6, "mascara-6-1"},
    {"Máscara (M-7 '1')", 14567, 1, 0.0041, -0.074, -0.577, -9, 0, 6, "mascara-7-1"},
    {"Máscara (M-7 '2')", 2872, 1, 0.0041, -0.074, -0.577, -9, 0, 6, "mascara-7-2"},
    {"Máscara (M-8 '1')", 2779, 1, 0.005, -0.094, -0.565, -10, 0, 6, "mascara-8-1"},
    {"Máscara (M-9 '1')", 2778, 1, 0.005, -0.090, -0.565, -10, 0, 6, "mascara-9-1"},
    {"Máscara (M-10 '1')", 2754, 1, 0.005, -0.090, -0.565, -10, 0, 6, "mascara-10-1"},
    {"Máscara (M-11 '1')", 2533, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-11-1"},
    {"Máscara (M-11 '2')", 2601, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-11-2"},
    {"Máscara (M-12 '1')", 1020, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-12-1"},
    {"Máscara (M-12 '2')", 2711, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-12-2"},
    {"Máscara (Halloween)", 2715, 1, 0.015, -0.139, -0.550, -15, 0, 7, "mascarah"}, 
 },

 [9] = {
    {"Máscara (M-1 '1')", 14582, 1, 0.0159, -0.25, -0.550, -15, 0, 5, "mascara-1-1"},
    {"Máscara (M-2 '1')", 2783, 1, 0.015, -0.139, -0.550, -15, 0, 7, "mascara-2-1"},
    {"Máscara (M-3 '1')", 3440, 1, 0.009, -0.090, -0.565, -10, 0, 6, "mascara-3-1"},
    {"Máscara (M-4 '1')", 3430, 1, 0.009, -0.090, -0.565, -10, 0, 6, "mascara-4-1"},
    {"Máscara (M-5 '1')", 2785, 1, 0.0045, -0.074, -0.570, -9, 0, 6, "mascara-5-1"},
    {"Máscara (M-5 '2')", 14566, 1, 0.0045, -0.074, -0.570, -9, 0, 6, "mascara-5-2"},
    {"Máscara (M-6 '1')", 14568, 1, 0.0045, -0.085, -0.570, -9, 0, 6, "mascara-6-1"},
    {"Máscara (M-7 '1')", 14567, 1, 0.0041, -0.074, -0.577, -9, 0, 6, "mascara-7-1"},
    {"Máscara (M-7 '2')", 2872, 1, 0.0041, -0.074, -0.577, -9, 0, 6, "mascara-7-2"},
    {"Máscara (M-8 '1')", 2779, 1, 0.005, -0.094, -0.565, -10, 0, 6, "mascara-8-1"},
    {"Máscara (M-9 '1')", 2778, 1, 0.005, -0.090, -0.565, -10, 0, 6, "mascara-9-1"},
    {"Máscara (M-10 '1')", 2754, 1, 0.005, -0.090, -0.565, -10, 0, 6, "mascara-10-1"},
    {"Máscara (M-11 '1')", 2533, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-11-1"},
    {"Máscara (M-11 '2')", 2601, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-11-2"},
    {"Máscara (M-12 '1')", 1020, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-12-1"},
    {"Máscara (M-12 '2')", 2711, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascara-12-2"},
    {"Máscara Halloween", 2711, 1, 0.008, -0.085, -0.565, -10, 0, 6, "mascarah"},
    --{"Máscara (Halloween)", 2715, 1, 0.005, -0.090, -0.565, -10, 0, 6, "mascarah"},
 },
}
]]